SELECT 'X' + C_UNIT_NO AS UnitNumber
		,EFFDT
FROM [dbo].[PS_C_UMPOSDATA_TBL_Full] posData
WHERE C_PROGTYPEPOLLED = 'starpos'
AND C_UNIT_NO LIKE '11%'
AND  EFFDT =
(
	SELECT MAX(EFFDT)
	FROM [dbo].[PS_C_UMPOSDATA_TBL_Full]
	WHERE C_UNIT_NO = posData.C_UNIT_NO
)
ORDER BY C_UNIT_NO
