INSERT INTO [Detail].[POSOrder]
           ([OrderId]
		   ,[TerminalID]
           ,[OrderNumber]
           ,[OrderDate]
           ,[EmployeeID]
           ,[DestinationID]
           ,[OrderType]
           ,[TotalNonFoodSale]
           ,[TotalFoodSale]
           ,[TotalTaxableSale]
           ,[TaxCollected]
           ,[PromoAmount]
           ,[PromoCount]
           ,[CouponAmount]
           ,[CouponCount]
           ,[FreeAmount]
           ,[FreeCount]
           ,[FCTTranID]
           ,[CentsOffAmount]
           ,[CentsOffCount]
           ,[CreditCardAmount]
           ,[GiftCardSaleAmount]
           ,[GiftCardSaleCount]
           ,[GiftCardRedemAmount]
           ,[GiftCardRedemCount]
           ,[DebitCardAmount]
           ,[CashBackAmount])
     VALUES
           (!ORDERID
           ,!TERMINALID
           ,!ORDERNUMBER
           ,'!ORDERDATE'
           ,!EMPLOYEEID
           ,!DESTINATIONID
           ,!ORDERTYPE
           ,!TOTALNONFOODSALE
           ,!TOTALFOODSALE
           ,!TOTALTAXABLESALE
           ,!TAXCOLLECTED
           ,!PROMOAMOUNT
           ,!PROMOCOUNT
           ,!COUPONAMOUNT
           ,!COUPONCOUNT
           ,!FREEAMOUNT
           ,!FREECOUNT
           ,!FCTTRANID
           ,!CENTSOFFAMOUNT
           ,!CENTSOFFCOUNT
           ,!CREDITCARDAMOUNT
           ,!GIFTCARDSALEAMOUNT
           ,!GIFTCARDSALECOUNT
           ,!GIFTCARDREDEMAMOUNT
           ,!GIFTCARDREDEMCOUNT
           ,!DEBITCARDAMOUNT
           ,!CASHBACKAMOUNT)



