//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrinkUnit
    {
        public string UnitNumber { get; set; }
        public string LocationToken { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string TimeZone { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int EntityId { get; set; }
        public System.TimeSpan BusinessDayStartTime { get; set; }
    }
}
