//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrinkTender
    {
        public int BrinkTenderId { get; set; }
        public string Name { get; set; }
        public int TenderTypeId { get; set; }
        public string TenderTypeName { get; set; }
    }
}
