//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrinkApiDataEntities : DbContext
    {
        public BrinkApiDataEntities()
            : base("name=BrinkApiDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrinkOrder> BrinkOrders { get; set; }
        public virtual DbSet<BrinkUnit> BrinkUnits { get; set; }
        public virtual DbSet<BrinkDestination> BrinkDestinations { get; set; }
        public virtual DbSet<DateDimension> DateDimensions { get; set; }
        public virtual DbSet<TimeSegment> TimeSegments { get; set; }
        public virtual DbSet<BrinkOrderPayment> BrinkOrderPayments { get; set; }
        public virtual DbSet<BrinkTender> BrinkTenders { get; set; }
        public virtual DbSet<RoyaltyEntity> RoyaltyEntities { get; set; }
        public virtual DbSet<RoyaltyUnit> RoyaltyUnits { get; set; }
        public virtual DbSet<CkePeriod> CkePeriods { get; set; }
        public virtual DbSet<BrinkPromo> BrinkPromoes { get; set; }
        public virtual DbSet<MenuItemPricing> MenuItemPricings { get; set; }
    }
}
