//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrinkOrderPayment
    {
        public int BrinkOrderPaymentId { get; set; }
        public int BrinkOrderId { get; set; }
        public System.DateTime BusinessDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Change { get; set; }
        public int Id { get; set; }
        public int TenderId { get; set; }
        public string Last4 { get; set; }
        public string AuthorizationCode { get; set; }
        public string ReferenceNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> MerchantAccountType { get; set; }
        public Nullable<decimal> TipAmount { get; set; }
    
        public virtual BrinkOrder BrinkOrder { get; set; }
    }
}
