#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataAnalysis")]
	public partial class CouponDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertScannedCoupon(ScannedCoupon instance);
    partial void UpdateScannedCoupon(ScannedCoupon instance);
    partial void DeleteScannedCoupon(ScannedCoupon instance);
    #endregion
		
		public CouponDataContext() : 
				base(global::TestOMatic2012.Properties.Settings.Default.DataAnalysisConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public CouponDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CouponDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CouponDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CouponDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ScannedCoupon> ScannedCoupons
		{
			get
			{
				return this.GetTable<ScannedCoupon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ScannedCoupon")]
	public partial class ScannedCoupon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ScannedCouponId;
		
		private string _RestaurantNumber;
		
		private string _OrderNumber;
		
		private string _RegisterNumber;
		
		private string _EmployeeNumber;
		
		private System.DateTime _TransactionTime;
		
		private string _Destination;
		
		private string _CouponId;
		
		private string _MenuItemDescription;
		
		private int _Quantity;
		
		private decimal _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnScannedCouponIdChanging(int value);
    partial void OnScannedCouponIdChanged();
    partial void OnRestaurantNumberChanging(string value);
    partial void OnRestaurantNumberChanged();
    partial void OnOrderNumberChanging(string value);
    partial void OnOrderNumberChanged();
    partial void OnRegisterNumberChanging(string value);
    partial void OnRegisterNumberChanged();
    partial void OnEmployeeNumberChanging(string value);
    partial void OnEmployeeNumberChanged();
    partial void OnTransactionTimeChanging(System.DateTime value);
    partial void OnTransactionTimeChanged();
    partial void OnDestinationChanging(string value);
    partial void OnDestinationChanged();
    partial void OnCouponIdChanging(string value);
    partial void OnCouponIdChanged();
    partial void OnMenuItemDescriptionChanging(string value);
    partial void OnMenuItemDescriptionChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    #endregion
		
		public ScannedCoupon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScannedCouponId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ScannedCouponId
		{
			get
			{
				return this._ScannedCouponId;
			}
			set
			{
				if ((this._ScannedCouponId != value))
				{
					this.OnScannedCouponIdChanging(value);
					this.SendPropertyChanging();
					this._ScannedCouponId = value;
					this.SendPropertyChanged("ScannedCouponId");
					this.OnScannedCouponIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestaurantNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RestaurantNumber
		{
			get
			{
				return this._RestaurantNumber;
			}
			set
			{
				if ((this._RestaurantNumber != value))
				{
					this.OnRestaurantNumberChanging(value);
					this.SendPropertyChanging();
					this._RestaurantNumber = value;
					this.SendPropertyChanged("RestaurantNumber");
					this.OnRestaurantNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RegisterNumber
		{
			get
			{
				return this._RegisterNumber;
			}
			set
			{
				if ((this._RegisterNumber != value))
				{
					this.OnRegisterNumberChanging(value);
					this.SendPropertyChanging();
					this._RegisterNumber = value;
					this.SendPropertyChanged("RegisterNumber");
					this.OnRegisterNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmployeeNumber
		{
			get
			{
				return this._EmployeeNumber;
			}
			set
			{
				if ((this._EmployeeNumber != value))
				{
					this.OnEmployeeNumberChanging(value);
					this.SendPropertyChanging();
					this._EmployeeNumber = value;
					this.SendPropertyChanged("EmployeeNumber");
					this.OnEmployeeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionTime", DbType="DateTime NOT NULL")]
		public System.DateTime TransactionTime
		{
			get
			{
				return this._TransactionTime;
			}
			set
			{
				if ((this._TransactionTime != value))
				{
					this.OnTransactionTimeChanging(value);
					this.SendPropertyChanging();
					this._TransactionTime = value;
					this.SendPropertyChanged("TransactionTime");
					this.OnTransactionTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				if ((this._Destination != value))
				{
					this.OnDestinationChanging(value);
					this.SendPropertyChanging();
					this._Destination = value;
					this.SendPropertyChanged("Destination");
					this.OnDestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouponId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CouponId
		{
			get
			{
				return this._CouponId;
			}
			set
			{
				if ((this._CouponId != value))
				{
					this.OnCouponIdChanging(value);
					this.SendPropertyChanging();
					this._CouponId = value;
					this.SendPropertyChanged("CouponId");
					this.OnCouponIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MenuItemDescription
		{
			get
			{
				return this._MenuItemDescription;
			}
			set
			{
				if ((this._MenuItemDescription != value))
				{
					this.OnMenuItemDescriptionChanging(value);
					this.SendPropertyChanging();
					this._MenuItemDescription = value;
					this.SendPropertyChanged("MenuItemDescription");
					this.OnMenuItemDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
