#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataAnalysis")]
	public partial class DataAnalysisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertErrorEmail(ErrorEmail instance);
    partial void UpdateErrorEmail(ErrorEmail instance);
    partial void DeleteErrorEmail(ErrorEmail instance);
    partial void InsertLaborHour(LaborHour instance);
    partial void UpdateLaborHour(LaborHour instance);
    partial void DeleteLaborHour(LaborHour instance);
    partial void InsertMenuMixFile(MenuMixFile instance);
    partial void UpdateMenuMixFile(MenuMixFile instance);
    partial void DeleteMenuMixFile(MenuMixFile instance);
    partial void InsertMenuMixItem(MenuMixItem instance);
    partial void UpdateMenuMixItem(MenuMixItem instance);
    partial void DeleteMenuMixItem(MenuMixItem instance);
    partial void InsertMenuMixPollItem(MenuMixPollItem instance);
    partial void UpdateMenuMixPollItem(MenuMixPollItem instance);
    partial void DeleteMenuMixPollItem(MenuMixPollItem instance);
    partial void InsertDepositDetail(DepositDetail instance);
    partial void UpdateDepositDetail(DepositDetail instance);
    partial void DeleteDepositDetail(DepositDetail instance);
    partial void InsertEpassDepositDetailFactArchive(EpassDepositDetailFactArchive instance);
    partial void UpdateEpassDepositDetailFactArchive(EpassDepositDetailFactArchive instance);
    partial void DeleteEpassDepositDetailFactArchive(EpassDepositDetailFactArchive instance);
    partial void InsertWin7Unit(Win7Unit instance);
    partial void UpdateWin7Unit(Win7Unit instance);
    partial void DeleteWin7Unit(Win7Unit instance);
    partial void InsertWeeklyLaborFile(WeeklyLaborFile instance);
    partial void UpdateWeeklyLaborFile(WeeklyLaborFile instance);
    partial void DeleteWeeklyLaborFile(WeeklyLaborFile instance);
    partial void InsertWeeklyLaborDetail(WeeklyLaborDetail instance);
    partial void UpdateWeeklyLaborDetail(WeeklyLaborDetail instance);
    partial void DeleteWeeklyLaborDetail(WeeklyLaborDetail instance);
    partial void InsertCouponOrder(CouponOrder instance);
    partial void UpdateCouponOrder(CouponOrder instance);
    partial void DeleteCouponOrder(CouponOrder instance);
    partial void InsertCouponData(CouponData instance);
    partial void UpdateCouponData(CouponData instance);
    partial void DeleteCouponData(CouponData instance);
    partial void InsertFinFileDetail(FinFileDetail instance);
    partial void UpdateFinFileDetail(FinFileDetail instance);
    partial void DeleteFinFileDetail(FinFileDetail instance);
    partial void InsertCreditCardSummary(CreditCardSummary instance);
    partial void UpdateCreditCardSummary(CreditCardSummary instance);
    partial void DeleteCreditCardSummary(CreditCardSummary instance);
    partial void InsertSettledCreditCard(SettledCreditCard instance);
    partial void UpdateSettledCreditCard(SettledCreditCard instance);
    partial void DeleteSettledCreditCard(SettledCreditCard instance);
    partial void InsertCreditCardDetail(CreditCardDetail instance);
    partial void UpdateCreditCardDetail(CreditCardDetail instance);
    partial void DeleteCreditCardDetail(CreditCardDetail instance);
    partial void InsertFinFile(FinFile instance);
    partial void UpdateFinFile(FinFile instance);
    partial void DeleteFinFile(FinFile instance);
    partial void InsertParentChildNumber(ParentChildNumber instance);
    partial void UpdateParentChildNumber(ParentChildNumber instance);
    partial void DeleteParentChildNumber(ParentChildNumber instance);
    #endregion
		
		public DataAnalysisDataContext() : 
				base(global::TestOMatic2012.Properties.Settings.Default.DataAnalysisConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public DataAnalysisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAnalysisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAnalysisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAnalysisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ErrorEmail> ErrorEmails
		{
			get
			{
				return this.GetTable<ErrorEmail>();
			}
		}
		
		public System.Data.Linq.Table<LaborHour> LaborHours
		{
			get
			{
				return this.GetTable<LaborHour>();
			}
		}
		
		public System.Data.Linq.Table<MenuMixFile> MenuMixFiles
		{
			get
			{
				return this.GetTable<MenuMixFile>();
			}
		}
		
		public System.Data.Linq.Table<MenuMixItem> MenuMixItems
		{
			get
			{
				return this.GetTable<MenuMixItem>();
			}
		}
		
		public System.Data.Linq.Table<MenuMixPollItem> MenuMixPollItems
		{
			get
			{
				return this.GetTable<MenuMixPollItem>();
			}
		}
		
		public System.Data.Linq.Table<DepositDetail> DepositDetails
		{
			get
			{
				return this.GetTable<DepositDetail>();
			}
		}
		
		public System.Data.Linq.Table<EpassDepositDetailFactArchive> EpassDepositDetailFactArchives
		{
			get
			{
				return this.GetTable<EpassDepositDetailFactArchive>();
			}
		}
		
		public System.Data.Linq.Table<Win7Unit> Win7Units
		{
			get
			{
				return this.GetTable<Win7Unit>();
			}
		}
		
		public System.Data.Linq.Table<WeeklyLaborFile> WeeklyLaborFiles
		{
			get
			{
				return this.GetTable<WeeklyLaborFile>();
			}
		}
		
		public System.Data.Linq.Table<WeeklyLaborDetail> WeeklyLaborDetails
		{
			get
			{
				return this.GetTable<WeeklyLaborDetail>();
			}
		}
		
		public System.Data.Linq.Table<CouponOrder> CouponOrders
		{
			get
			{
				return this.GetTable<CouponOrder>();
			}
		}
		
		public System.Data.Linq.Table<CouponData> CouponDatas
		{
			get
			{
				return this.GetTable<CouponData>();
			}
		}
		
		public System.Data.Linq.Table<FinFileDetail> FinFileDetails
		{
			get
			{
				return this.GetTable<FinFileDetail>();
			}
		}
		
		public System.Data.Linq.Table<CreditCardSummary> CreditCardSummaries
		{
			get
			{
				return this.GetTable<CreditCardSummary>();
			}
		}
		
		public System.Data.Linq.Table<SettledCreditCard> SettledCreditCards
		{
			get
			{
				return this.GetTable<SettledCreditCard>();
			}
		}
		
		public System.Data.Linq.Table<CreditCardDetail> CreditCardDetails
		{
			get
			{
				return this.GetTable<CreditCardDetail>();
			}
		}
		
		public System.Data.Linq.Table<FinFile> FinFiles
		{
			get
			{
				return this.GetTable<FinFile>();
			}
		}
		
		public System.Data.Linq.Table<ParentChildNumber> ParentChildNumbers
		{
			get
			{
				return this.GetTable<ParentChildNumber>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ErrorEmail")]
	public partial class ErrorEmail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ErrorEmailId;
		
		private string _UnitNumber;
		
		private System.DateTime _ErrorDate;
		
		private string _ErrorType;
		
		private string _ErrorMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnErrorEmailIdChanging(int value);
    partial void OnErrorEmailIdChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnErrorDateChanging(System.DateTime value);
    partial void OnErrorDateChanged();
    partial void OnErrorTypeChanging(string value);
    partial void OnErrorTypeChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    #endregion
		
		public ErrorEmail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorEmailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ErrorEmailId
		{
			get
			{
				return this._ErrorEmailId;
			}
			set
			{
				if ((this._ErrorEmailId != value))
				{
					this.OnErrorEmailIdChanging(value);
					this.SendPropertyChanging();
					this._ErrorEmailId = value;
					this.SendPropertyChanged("ErrorEmailId");
					this.OnErrorEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorDate", DbType="DateTime NOT NULL")]
		public System.DateTime ErrorDate
		{
			get
			{
				return this._ErrorDate;
			}
			set
			{
				if ((this._ErrorDate != value))
				{
					this.OnErrorDateChanging(value);
					this.SendPropertyChanging();
					this._ErrorDate = value;
					this.SendPropertyChanged("ErrorDate");
					this.OnErrorDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ErrorType
		{
			get
			{
				return this._ErrorType;
			}
			set
			{
				if ((this._ErrorType != value))
				{
					this.OnErrorTypeChanging(value);
					this.SendPropertyChanging();
					this._ErrorType = value;
					this.SendPropertyChanged("ErrorType");
					this.OnErrorTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LaborHours")]
	public partial class LaborHour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LaborHoursId;
		
		private string _UnitNumber;
		
		private string _SSN;
		
		private decimal _Hours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLaborHoursIdChanging(int value);
    partial void OnLaborHoursIdChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnHoursChanging(decimal value);
    partial void OnHoursChanged();
    #endregion
		
		public LaborHour()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaborHoursId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LaborHoursId
		{
			get
			{
				return this._LaborHoursId;
			}
			set
			{
				if ((this._LaborHoursId != value))
				{
					this.OnLaborHoursIdChanging(value);
					this.SendPropertyChanging();
					this._LaborHoursId = value;
					this.SendPropertyChanged("LaborHoursId");
					this.OnLaborHoursIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hours", DbType="Decimal(18,2) NOT NULL")]
		public decimal Hours
		{
			get
			{
				return this._Hours;
			}
			set
			{
				if ((this._Hours != value))
				{
					this.OnHoursChanging(value);
					this.SendPropertyChanging();
					this._Hours = value;
					this.SendPropertyChanged("Hours");
					this.OnHoursChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuMixFile")]
	public partial class MenuMixFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuMixFileId;
		
		private string _FileName;
		
		private System.DateTime _FileDate;
		
		private System.DateTime _CreateDate;
		
		private EntitySet<MenuMixPollItem> _MenuMixPollItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuMixFileIdChanging(int value);
    partial void OnMenuMixFileIdChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFileDateChanging(System.DateTime value);
    partial void OnFileDateChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
		
		public MenuMixFile()
		{
			this._MenuMixPollItems = new EntitySet<MenuMixPollItem>(new Action<MenuMixPollItem>(this.attach_MenuMixPollItems), new Action<MenuMixPollItem>(this.detach_MenuMixPollItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuMixFileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MenuMixFileId
		{
			get
			{
				return this._MenuMixFileId;
			}
			set
			{
				if ((this._MenuMixFileId != value))
				{
					this.OnMenuMixFileIdChanging(value);
					this.SendPropertyChanging();
					this._MenuMixFileId = value;
					this.SendPropertyChanged("MenuMixFileId");
					this.OnMenuMixFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDate", DbType="DateTime NOT NULL")]
		public System.DateTime FileDate
		{
			get
			{
				return this._FileDate;
			}
			set
			{
				if ((this._FileDate != value))
				{
					this.OnFileDateChanging(value);
					this.SendPropertyChanging();
					this._FileDate = value;
					this.SendPropertyChanged("FileDate");
					this.OnFileDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuMixFile_MenuMixPollItem", Storage="_MenuMixPollItems", ThisKey="MenuMixFileId", OtherKey="MenuMixFileId")]
		public EntitySet<MenuMixPollItem> MenuMixPollItems
		{
			get
			{
				return this._MenuMixPollItems;
			}
			set
			{
				this._MenuMixPollItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MenuMixPollItems(MenuMixPollItem entity)
		{
			this.SendPropertyChanging();
			entity.MenuMixFile = this;
		}
		
		private void detach_MenuMixPollItems(MenuMixPollItem entity)
		{
			this.SendPropertyChanging();
			entity.MenuMixFile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuMixItem")]
	public partial class MenuMixItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuMixItemId;
		
		private string _MenuItemCode;
		
		private string _Description;
		
		private System.DateTime _CreateDate;
		
		private EntitySet<MenuMixPollItem> _MenuMixPollItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuMixItemIdChanging(int value);
    partial void OnMenuMixItemIdChanged();
    partial void OnMenuItemCodeChanging(string value);
    partial void OnMenuItemCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
		
		public MenuMixItem()
		{
			this._MenuMixPollItems = new EntitySet<MenuMixPollItem>(new Action<MenuMixPollItem>(this.attach_MenuMixPollItems), new Action<MenuMixPollItem>(this.detach_MenuMixPollItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuMixItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MenuMixItemId
		{
			get
			{
				return this._MenuMixItemId;
			}
			set
			{
				if ((this._MenuMixItemId != value))
				{
					this.OnMenuMixItemIdChanging(value);
					this.SendPropertyChanging();
					this._MenuMixItemId = value;
					this.SendPropertyChanged("MenuMixItemId");
					this.OnMenuMixItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MenuItemCode
		{
			get
			{
				return this._MenuItemCode;
			}
			set
			{
				if ((this._MenuItemCode != value))
				{
					this.OnMenuItemCodeChanging(value);
					this.SendPropertyChanging();
					this._MenuItemCode = value;
					this.SendPropertyChanged("MenuItemCode");
					this.OnMenuItemCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuMixItem_MenuMixPollItem", Storage="_MenuMixPollItems", ThisKey="MenuMixItemId", OtherKey="MenuMixItemId")]
		public EntitySet<MenuMixPollItem> MenuMixPollItems
		{
			get
			{
				return this._MenuMixPollItems;
			}
			set
			{
				this._MenuMixPollItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MenuMixPollItems(MenuMixPollItem entity)
		{
			this.SendPropertyChanging();
			entity.MenuMixItem = this;
		}
		
		private void detach_MenuMixPollItems(MenuMixPollItem entity)
		{
			this.SendPropertyChanging();
			entity.MenuMixItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuMixPollItem")]
	public partial class MenuMixPollItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuMixPollItemId;
		
		private int _MenuMixFileId;
		
		private string _UnitNumber;
		
		private int _MenuMixItemId;
		
		private decimal _Price;
		
		private int _Quantity;
		
		private decimal _TotalAmount;
		
		private System.DateTime _CreateDate;
		
		private EntityRef<MenuMixFile> _MenuMixFile;
		
		private EntityRef<MenuMixItem> _MenuMixItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuMixPollItemIdChanging(int value);
    partial void OnMenuMixPollItemIdChanged();
    partial void OnMenuMixFileIdChanging(int value);
    partial void OnMenuMixFileIdChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnMenuMixItemIdChanging(int value);
    partial void OnMenuMixItemIdChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnTotalAmountChanging(decimal value);
    partial void OnTotalAmountChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
		
		public MenuMixPollItem()
		{
			this._MenuMixFile = default(EntityRef<MenuMixFile>);
			this._MenuMixItem = default(EntityRef<MenuMixItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuMixPollItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MenuMixPollItemId
		{
			get
			{
				return this._MenuMixPollItemId;
			}
			set
			{
				if ((this._MenuMixPollItemId != value))
				{
					this.OnMenuMixPollItemIdChanging(value);
					this.SendPropertyChanging();
					this._MenuMixPollItemId = value;
					this.SendPropertyChanged("MenuMixPollItemId");
					this.OnMenuMixPollItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuMixFileId", DbType="Int NOT NULL")]
		public int MenuMixFileId
		{
			get
			{
				return this._MenuMixFileId;
			}
			set
			{
				if ((this._MenuMixFileId != value))
				{
					if (this._MenuMixFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuMixFileIdChanging(value);
					this.SendPropertyChanging();
					this._MenuMixFileId = value;
					this.SendPropertyChanged("MenuMixFileId");
					this.OnMenuMixFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuMixItemId", DbType="Int NOT NULL")]
		public int MenuMixItemId
		{
			get
			{
				return this._MenuMixItemId;
			}
			set
			{
				if ((this._MenuMixItemId != value))
				{
					if (this._MenuMixItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuMixItemIdChanging(value);
					this.SendPropertyChanging();
					this._MenuMixItemId = value;
					this.SendPropertyChanged("MenuMixItemId");
					this.OnMenuMixItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,2) NOT NULL")]
		public decimal TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this.OnTotalAmountChanging(value);
					this.SendPropertyChanging();
					this._TotalAmount = value;
					this.SendPropertyChanged("TotalAmount");
					this.OnTotalAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuMixFile_MenuMixPollItem", Storage="_MenuMixFile", ThisKey="MenuMixFileId", OtherKey="MenuMixFileId", IsForeignKey=true)]
		public MenuMixFile MenuMixFile
		{
			get
			{
				return this._MenuMixFile.Entity;
			}
			set
			{
				MenuMixFile previousValue = this._MenuMixFile.Entity;
				if (((previousValue != value) 
							|| (this._MenuMixFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MenuMixFile.Entity = null;
						previousValue.MenuMixPollItems.Remove(this);
					}
					this._MenuMixFile.Entity = value;
					if ((value != null))
					{
						value.MenuMixPollItems.Add(this);
						this._MenuMixFileId = value.MenuMixFileId;
					}
					else
					{
						this._MenuMixFileId = default(int);
					}
					this.SendPropertyChanged("MenuMixFile");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuMixItem_MenuMixPollItem", Storage="_MenuMixItem", ThisKey="MenuMixItemId", OtherKey="MenuMixItemId", IsForeignKey=true)]
		public MenuMixItem MenuMixItem
		{
			get
			{
				return this._MenuMixItem.Entity;
			}
			set
			{
				MenuMixItem previousValue = this._MenuMixItem.Entity;
				if (((previousValue != value) 
							|| (this._MenuMixItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MenuMixItem.Entity = null;
						previousValue.MenuMixPollItems.Remove(this);
					}
					this._MenuMixItem.Entity = value;
					if ((value != null))
					{
						value.MenuMixPollItems.Add(this);
						this._MenuMixItemId = value.MenuMixItemId;
					}
					else
					{
						this._MenuMixItemId = default(int);
					}
					this.SendPropertyChanged("MenuMixItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DepositDetail")]
	public partial class DepositDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DepositDetailId;
		
		private string _UnitNumber;
		
		private System.DateTime _DepositDate;
		
		private decimal _Amount;
		
		private string _Status;
		
		private int _HFSDB_DepositId;
		
		private System.DateTime _CreateDateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDepositDetailIdChanging(int value);
    partial void OnDepositDetailIdChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnDepositDateChanging(System.DateTime value);
    partial void OnDepositDateChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnHFSDB_DepositIdChanging(int value);
    partial void OnHFSDB_DepositIdChanged();
    partial void OnCreateDateTimeChanging(System.DateTime value);
    partial void OnCreateDateTimeChanged();
    #endregion
		
		public DepositDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepositDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DepositDetailId
		{
			get
			{
				return this._DepositDetailId;
			}
			set
			{
				if ((this._DepositDetailId != value))
				{
					this.OnDepositDetailIdChanging(value);
					this.SendPropertyChanging();
					this._DepositDetailId = value;
					this.SendPropertyChanged("DepositDetailId");
					this.OnDepositDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepositDate", DbType="DateTime NOT NULL")]
		public System.DateTime DepositDate
		{
			get
			{
				return this._DepositDate;
			}
			set
			{
				if ((this._DepositDate != value))
				{
					this.OnDepositDateChanging(value);
					this.SendPropertyChanging();
					this._DepositDate = value;
					this.SendPropertyChanged("DepositDate");
					this.OnDepositDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HFSDB_DepositId", DbType="Int NOT NULL")]
		public int HFSDB_DepositId
		{
			get
			{
				return this._HFSDB_DepositId;
			}
			set
			{
				if ((this._HFSDB_DepositId != value))
				{
					this.OnHFSDB_DepositIdChanging(value);
					this.SendPropertyChanging();
					this._HFSDB_DepositId = value;
					this.SendPropertyChanged("HFSDB_DepositId");
					this.OnHFSDB_DepositIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDateTime
		{
			get
			{
				return this._CreateDateTime;
			}
			set
			{
				if ((this._CreateDateTime != value))
				{
					this.OnCreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateDateTime = value;
					this.SendPropertyChanged("CreateDateTime");
					this.OnCreateDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EpassDepositDetailFactArchive")]
	public partial class EpassDepositDetailFactArchive : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _deposit_dtl_id;
		
		private int _deposit_id;
		
		private int _POS_fact_id;
		
		private int _System_id;
		
		private int _Restaurant_no;
		
		private System.DateTime _Cal_Date;
		
		private System.Nullable<decimal> _Deposit_amt;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private string _create_by;
		
		private System.Nullable<System.DateTime> _last_chg_date;
		
		private string _last_chg_by;
		
		private string _source;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondeposit_dtl_idChanging(int value);
    partial void Ondeposit_dtl_idChanged();
    partial void Ondeposit_idChanging(int value);
    partial void Ondeposit_idChanged();
    partial void OnPOS_fact_idChanging(int value);
    partial void OnPOS_fact_idChanged();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnRestaurant_noChanging(int value);
    partial void OnRestaurant_noChanged();
    partial void OnCal_DateChanging(System.DateTime value);
    partial void OnCal_DateChanged();
    partial void OnDeposit_amtChanging(System.Nullable<decimal> value);
    partial void OnDeposit_amtChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void Oncreate_byChanging(string value);
    partial void Oncreate_byChanged();
    partial void Onlast_chg_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_chg_dateChanged();
    partial void Onlast_chg_byChanging(string value);
    partial void Onlast_chg_byChanged();
    partial void OnsourceChanging(string value);
    partial void OnsourceChanged();
    #endregion
		
		public EpassDepositDetailFactArchive()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deposit_dtl_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int deposit_dtl_id
		{
			get
			{
				return this._deposit_dtl_id;
			}
			set
			{
				if ((this._deposit_dtl_id != value))
				{
					this.Ondeposit_dtl_idChanging(value);
					this.SendPropertyChanging();
					this._deposit_dtl_id = value;
					this.SendPropertyChanged("deposit_dtl_id");
					this.Ondeposit_dtl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deposit_id", DbType="Int NOT NULL")]
		public int deposit_id
		{
			get
			{
				return this._deposit_id;
			}
			set
			{
				if ((this._deposit_id != value))
				{
					this.Ondeposit_idChanging(value);
					this.SendPropertyChanging();
					this._deposit_id = value;
					this.SendPropertyChanged("deposit_id");
					this.Ondeposit_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_fact_id", DbType="Int NOT NULL")]
		public int POS_fact_id
		{
			get
			{
				return this._POS_fact_id;
			}
			set
			{
				if ((this._POS_fact_id != value))
				{
					this.OnPOS_fact_idChanging(value);
					this.SendPropertyChanging();
					this._POS_fact_id = value;
					this.SendPropertyChanged("POS_fact_id");
					this.OnPOS_fact_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", DbType="Int NOT NULL")]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Restaurant_no", DbType="Int NOT NULL")]
		public int Restaurant_no
		{
			get
			{
				return this._Restaurant_no;
			}
			set
			{
				if ((this._Restaurant_no != value))
				{
					this.OnRestaurant_noChanging(value);
					this.SendPropertyChanging();
					this._Restaurant_no = value;
					this.SendPropertyChanged("Restaurant_no");
					this.OnRestaurant_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cal_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Cal_Date
		{
			get
			{
				return this._Cal_Date;
			}
			set
			{
				if ((this._Cal_Date != value))
				{
					this.OnCal_DateChanging(value);
					this.SendPropertyChanging();
					this._Cal_Date = value;
					this.SendPropertyChanged("Cal_Date");
					this.OnCal_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deposit_amt", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> Deposit_amt
		{
			get
			{
				return this._Deposit_amt;
			}
			set
			{
				if ((this._Deposit_amt != value))
				{
					this.OnDeposit_amtChanging(value);
					this.SendPropertyChanging();
					this._Deposit_amt = value;
					this.SendPropertyChanged("Deposit_amt");
					this.OnDeposit_amtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_by", DbType="VarChar(20)")]
		public string create_by
		{
			get
			{
				return this._create_by;
			}
			set
			{
				if ((this._create_by != value))
				{
					this.Oncreate_byChanging(value);
					this.SendPropertyChanging();
					this._create_by = value;
					this.SendPropertyChanged("create_by");
					this.Oncreate_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_chg_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_chg_date
		{
			get
			{
				return this._last_chg_date;
			}
			set
			{
				if ((this._last_chg_date != value))
				{
					this.Onlast_chg_dateChanging(value);
					this.SendPropertyChanging();
					this._last_chg_date = value;
					this.SendPropertyChanged("last_chg_date");
					this.Onlast_chg_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_chg_by", DbType="VarChar(20)")]
		public string last_chg_by
		{
			get
			{
				return this._last_chg_by;
			}
			set
			{
				if ((this._last_chg_by != value))
				{
					this.Onlast_chg_byChanging(value);
					this.SendPropertyChanging();
					this._last_chg_by = value;
					this.SendPropertyChanged("last_chg_by");
					this.Onlast_chg_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source", DbType="VarChar(2)")]
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				if ((this._source != value))
				{
					this.OnsourceChanging(value);
					this.SendPropertyChanging();
					this._source = value;
					this.SendPropertyChanged("source");
					this.OnsourceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Win7Units")]
	public partial class Win7Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RestaurantNo;
		
		private string _UnitNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRestaurantNoChanging(int value);
    partial void OnRestaurantNoChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    #endregion
		
		public Win7Unit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestaurantNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RestaurantNo
		{
			get
			{
				return this._RestaurantNo;
			}
			set
			{
				if ((this._RestaurantNo != value))
				{
					this.OnRestaurantNoChanging(value);
					this.SendPropertyChanging();
					this._RestaurantNo = value;
					this.SendPropertyChanged("RestaurantNo");
					this.OnRestaurantNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WeeklyLaborFile")]
	public partial class WeeklyLaborFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WeeklyLaborFileId;
		
		private string _UnitNumber;
		
		private string _FileName;
		
		private System.DateTime _FileDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWeeklyLaborFileIdChanging(int value);
    partial void OnWeeklyLaborFileIdChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFileDateChanging(System.DateTime value);
    partial void OnFileDateChanged();
    #endregion
		
		public WeeklyLaborFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeeklyLaborFileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WeeklyLaborFileId
		{
			get
			{
				return this._WeeklyLaborFileId;
			}
			set
			{
				if ((this._WeeklyLaborFileId != value))
				{
					this.OnWeeklyLaborFileIdChanging(value);
					this.SendPropertyChanging();
					this._WeeklyLaborFileId = value;
					this.SendPropertyChanged("WeeklyLaborFileId");
					this.OnWeeklyLaborFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDate", DbType="DateTime NOT NULL")]
		public System.DateTime FileDate
		{
			get
			{
				return this._FileDate;
			}
			set
			{
				if ((this._FileDate != value))
				{
					this.OnFileDateChanging(value);
					this.SendPropertyChanging();
					this._FileDate = value;
					this.SendPropertyChanged("FileDate");
					this.OnFileDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WeeklyLaborDetail")]
	public partial class WeeklyLaborDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WeekLaborDetailId;
		
		private int _WeekLaborFileId;
		
		private System.DateTime _BusinessDate;
		
		private decimal _RegularPayCrew;
		
		private decimal _RegularPayLeader;
		
		private decimal _OverTimePayCrew;
		
		private decimal _OverTimePayLeader;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWeekLaborDetailIdChanging(int value);
    partial void OnWeekLaborDetailIdChanged();
    partial void OnWeekLaborFileIdChanging(int value);
    partial void OnWeekLaborFileIdChanged();
    partial void OnBusinessDateChanging(System.DateTime value);
    partial void OnBusinessDateChanged();
    partial void OnRegularPayCrewChanging(decimal value);
    partial void OnRegularPayCrewChanged();
    partial void OnRegularPayLeaderChanging(decimal value);
    partial void OnRegularPayLeaderChanged();
    partial void OnOverTimePayCrewChanging(decimal value);
    partial void OnOverTimePayCrewChanged();
    partial void OnOverTimePayLeaderChanging(decimal value);
    partial void OnOverTimePayLeaderChanged();
    #endregion
		
		public WeeklyLaborDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekLaborDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WeekLaborDetailId
		{
			get
			{
				return this._WeekLaborDetailId;
			}
			set
			{
				if ((this._WeekLaborDetailId != value))
				{
					this.OnWeekLaborDetailIdChanging(value);
					this.SendPropertyChanging();
					this._WeekLaborDetailId = value;
					this.SendPropertyChanged("WeekLaborDetailId");
					this.OnWeekLaborDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekLaborFileId", DbType="Int NOT NULL")]
		public int WeekLaborFileId
		{
			get
			{
				return this._WeekLaborFileId;
			}
			set
			{
				if ((this._WeekLaborFileId != value))
				{
					this.OnWeekLaborFileIdChanging(value);
					this.SendPropertyChanging();
					this._WeekLaborFileId = value;
					this.SendPropertyChanged("WeekLaborFileId");
					this.OnWeekLaborFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="Date NOT NULL")]
		public System.DateTime BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this.OnBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._BusinessDate = value;
					this.SendPropertyChanged("BusinessDate");
					this.OnBusinessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegularPayCrew", DbType="Decimal(18,4) NOT NULL")]
		public decimal RegularPayCrew
		{
			get
			{
				return this._RegularPayCrew;
			}
			set
			{
				if ((this._RegularPayCrew != value))
				{
					this.OnRegularPayCrewChanging(value);
					this.SendPropertyChanging();
					this._RegularPayCrew = value;
					this.SendPropertyChanged("RegularPayCrew");
					this.OnRegularPayCrewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegularPayLeader", DbType="Decimal(18,4) NOT NULL")]
		public decimal RegularPayLeader
		{
			get
			{
				return this._RegularPayLeader;
			}
			set
			{
				if ((this._RegularPayLeader != value))
				{
					this.OnRegularPayLeaderChanging(value);
					this.SendPropertyChanging();
					this._RegularPayLeader = value;
					this.SendPropertyChanged("RegularPayLeader");
					this.OnRegularPayLeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverTimePayCrew", DbType="Decimal(18,4) NOT NULL")]
		public decimal OverTimePayCrew
		{
			get
			{
				return this._OverTimePayCrew;
			}
			set
			{
				if ((this._OverTimePayCrew != value))
				{
					this.OnOverTimePayCrewChanging(value);
					this.SendPropertyChanging();
					this._OverTimePayCrew = value;
					this.SendPropertyChanged("OverTimePayCrew");
					this.OnOverTimePayCrewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverTimePayLeader", DbType="Decimal(18,4) NOT NULL")]
		public decimal OverTimePayLeader
		{
			get
			{
				return this._OverTimePayLeader;
			}
			set
			{
				if ((this._OverTimePayLeader != value))
				{
					this.OnOverTimePayLeaderChanging(value);
					this.SendPropertyChanging();
					this._OverTimePayLeader = value;
					this.SendPropertyChanged("OverTimePayLeader");
					this.OnOverTimePayLeaderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CouponOrders")]
	public partial class CouponOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CouponOrdersId;
		
		private string _UnitNumber;
		
		private System.Nullable<System.DateTime> _BusinessDate;
		
		private System.Nullable<int> _Quantity;
		
		private System.Nullable<decimal> _Amount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCouponOrdersIdChanging(int value);
    partial void OnCouponOrdersIdChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnBusinessDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBusinessDateChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    #endregion
		
		public CouponOrder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouponOrdersId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CouponOrdersId
		{
			get
			{
				return this._CouponOrdersId;
			}
			set
			{
				if ((this._CouponOrdersId != value))
				{
					this.OnCouponOrdersIdChanging(value);
					this.SendPropertyChanging();
					this._CouponOrdersId = value;
					this.SendPropertyChanged("CouponOrdersId");
					this.OnCouponOrdersIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(50)")]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this.OnBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._BusinessDate = value;
					this.SendPropertyChanged("BusinessDate");
					this.OnBusinessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CouponData")]
	public partial class CouponData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CouponDataId;
		
		private int _CouponId;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCouponDataIdChanging(int value);
    partial void OnCouponDataIdChanged();
    partial void OnCouponIdChanging(int value);
    partial void OnCouponIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public CouponData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouponDataId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CouponDataId
		{
			get
			{
				return this._CouponDataId;
			}
			set
			{
				if ((this._CouponDataId != value))
				{
					this.OnCouponDataIdChanging(value);
					this.SendPropertyChanging();
					this._CouponDataId = value;
					this.SendPropertyChanged("CouponDataId");
					this.OnCouponDataIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouponId", DbType="Int NOT NULL")]
		public int CouponId
		{
			get
			{
				return this._CouponId;
			}
			set
			{
				if ((this._CouponId != value))
				{
					this.OnCouponIdChanging(value);
					this.SendPropertyChanging();
					this._CouponId = value;
					this.SendPropertyChanged("CouponId");
					this.OnCouponIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FinFileDetail")]
	public partial class FinFileDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FinFileDetailId;
		
		private int _FinFileId;
		
		private int _LineIndex;
		
		private string _Descriptor;
		
		private int _Count;
		
		private decimal _Amount;
		
		private EntityRef<FinFile> _FinFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFinFileDetailIdChanging(int value);
    partial void OnFinFileDetailIdChanged();
    partial void OnFinFileIdChanging(int value);
    partial void OnFinFileIdChanged();
    partial void OnLineIndexChanging(int value);
    partial void OnLineIndexChanged();
    partial void OnDescriptorChanging(string value);
    partial void OnDescriptorChanged();
    partial void OnCountChanging(int value);
    partial void OnCountChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    #endregion
		
		public FinFileDetail()
		{
			this._FinFile = default(EntityRef<FinFile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinFileDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FinFileDetailId
		{
			get
			{
				return this._FinFileDetailId;
			}
			set
			{
				if ((this._FinFileDetailId != value))
				{
					this.OnFinFileDetailIdChanging(value);
					this.SendPropertyChanging();
					this._FinFileDetailId = value;
					this.SendPropertyChanged("FinFileDetailId");
					this.OnFinFileDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinFileId", DbType="Int NOT NULL")]
		public int FinFileId
		{
			get
			{
				return this._FinFileId;
			}
			set
			{
				if ((this._FinFileId != value))
				{
					if (this._FinFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFinFileIdChanging(value);
					this.SendPropertyChanging();
					this._FinFileId = value;
					this.SendPropertyChanged("FinFileId");
					this.OnFinFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineIndex", DbType="Int NOT NULL")]
		public int LineIndex
		{
			get
			{
				return this._LineIndex;
			}
			set
			{
				if ((this._LineIndex != value))
				{
					this.OnLineIndexChanging(value);
					this.SendPropertyChanging();
					this._LineIndex = value;
					this.SendPropertyChanged("LineIndex");
					this.OnLineIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriptor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descriptor
		{
			get
			{
				return this._Descriptor;
			}
			set
			{
				if ((this._Descriptor != value))
				{
					this.OnDescriptorChanging(value);
					this.SendPropertyChanging();
					this._Descriptor = value;
					this.SendPropertyChanged("Descriptor");
					this.OnDescriptorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", DbType="Int NOT NULL")]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FinFile_FinFileDetail", Storage="_FinFile", ThisKey="FinFileId", OtherKey="FinFileId", IsForeignKey=true)]
		public FinFile FinFile
		{
			get
			{
				return this._FinFile.Entity;
			}
			set
			{
				FinFile previousValue = this._FinFile.Entity;
				if (((previousValue != value) 
							|| (this._FinFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FinFile.Entity = null;
						previousValue.FinFileDetails.Remove(this);
					}
					this._FinFile.Entity = value;
					if ((value != null))
					{
						value.FinFileDetails.Add(this);
						this._FinFileId = value.FinFileId;
					}
					else
					{
						this._FinFileId = default(int);
					}
					this.SendPropertyChanged("FinFile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CreditCardSummary")]
	public partial class CreditCardSummary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CreditCardSummaryId;
		
		private int _RestaurantNo;
		
		private System.DateTime _CalDate;
		
		private decimal _Amount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreditCardSummaryIdChanging(int value);
    partial void OnCreditCardSummaryIdChanged();
    partial void OnRestaurantNoChanging(int value);
    partial void OnRestaurantNoChanged();
    partial void OnCalDateChanging(System.DateTime value);
    partial void OnCalDateChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    #endregion
		
		public CreditCardSummary()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardSummaryId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CreditCardSummaryId
		{
			get
			{
				return this._CreditCardSummaryId;
			}
			set
			{
				if ((this._CreditCardSummaryId != value))
				{
					this.OnCreditCardSummaryIdChanging(value);
					this.SendPropertyChanging();
					this._CreditCardSummaryId = value;
					this.SendPropertyChanged("CreditCardSummaryId");
					this.OnCreditCardSummaryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestaurantNo", DbType="Int NOT NULL")]
		public int RestaurantNo
		{
			get
			{
				return this._RestaurantNo;
			}
			set
			{
				if ((this._RestaurantNo != value))
				{
					this.OnRestaurantNoChanging(value);
					this.SendPropertyChanging();
					this._RestaurantNo = value;
					this.SendPropertyChanged("RestaurantNo");
					this.OnRestaurantNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalDate", DbType="DateTime NOT NULL")]
		public System.DateTime CalDate
		{
			get
			{
				return this._CalDate;
			}
			set
			{
				if ((this._CalDate != value))
				{
					this.OnCalDateChanging(value);
					this.SendPropertyChanging();
					this._CalDate = value;
					this.SendPropertyChanged("CalDate");
					this.OnCalDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SettledCreditCard")]
	public partial class SettledCreditCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SettledCreditCardId;
		
		private int _RestaurantNo;
		
		private string _ReferenceNo;
		
		private string _Terminal;
		
		private string _Account;
		
		private string _UserId;
		
		private decimal _Amount;
		
		private string _AuthId;
		
		private System.DateTime _OriginalAuthDateTime;
		
		private System.DateTime _TransDateTime;
		
		private string _TransCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSettledCreditCardIdChanging(int value);
    partial void OnSettledCreditCardIdChanged();
    partial void OnRestaurantNoChanging(int value);
    partial void OnRestaurantNoChanged();
    partial void OnReferenceNoChanging(string value);
    partial void OnReferenceNoChanged();
    partial void OnTerminalChanging(string value);
    partial void OnTerminalChanged();
    partial void OnAccountChanging(string value);
    partial void OnAccountChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnAuthIdChanging(string value);
    partial void OnAuthIdChanged();
    partial void OnOriginalAuthDateTimeChanging(System.DateTime value);
    partial void OnOriginalAuthDateTimeChanged();
    partial void OnTransDateTimeChanging(System.DateTime value);
    partial void OnTransDateTimeChanged();
    partial void OnTransCodeChanging(string value);
    partial void OnTransCodeChanged();
    #endregion
		
		public SettledCreditCard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettledCreditCardId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SettledCreditCardId
		{
			get
			{
				return this._SettledCreditCardId;
			}
			set
			{
				if ((this._SettledCreditCardId != value))
				{
					this.OnSettledCreditCardIdChanging(value);
					this.SendPropertyChanging();
					this._SettledCreditCardId = value;
					this.SendPropertyChanged("SettledCreditCardId");
					this.OnSettledCreditCardIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestaurantNo", DbType="Int NOT NULL")]
		public int RestaurantNo
		{
			get
			{
				return this._RestaurantNo;
			}
			set
			{
				if ((this._RestaurantNo != value))
				{
					this.OnRestaurantNoChanging(value);
					this.SendPropertyChanging();
					this._RestaurantNo = value;
					this.SendPropertyChanged("RestaurantNo");
					this.OnRestaurantNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReferenceNo
		{
			get
			{
				return this._ReferenceNo;
			}
			set
			{
				if ((this._ReferenceNo != value))
				{
					this.OnReferenceNoChanging(value);
					this.SendPropertyChanging();
					this._ReferenceNo = value;
					this.SendPropertyChanged("ReferenceNo");
					this.OnReferenceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terminal", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Terminal
		{
			get
			{
				return this._Terminal;
			}
			set
			{
				if ((this._Terminal != value))
				{
					this.OnTerminalChanging(value);
					this.SendPropertyChanging();
					this._Terminal = value;
					this.SendPropertyChanged("Terminal");
					this.OnTerminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this.OnAccountChanging(value);
					this.SendPropertyChanging();
					this._Account = value;
					this.SendPropertyChanged("Account");
					this.OnAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AuthId
		{
			get
			{
				return this._AuthId;
			}
			set
			{
				if ((this._AuthId != value))
				{
					this.OnAuthIdChanging(value);
					this.SendPropertyChanging();
					this._AuthId = value;
					this.SendPropertyChanged("AuthId");
					this.OnAuthIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalAuthDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime OriginalAuthDateTime
		{
			get
			{
				return this._OriginalAuthDateTime;
			}
			set
			{
				if ((this._OriginalAuthDateTime != value))
				{
					this.OnOriginalAuthDateTimeChanging(value);
					this.SendPropertyChanging();
					this._OriginalAuthDateTime = value;
					this.SendPropertyChanged("OriginalAuthDateTime");
					this.OnOriginalAuthDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime TransDateTime
		{
			get
			{
				return this._TransDateTime;
			}
			set
			{
				if ((this._TransDateTime != value))
				{
					this.OnTransDateTimeChanging(value);
					this.SendPropertyChanging();
					this._TransDateTime = value;
					this.SendPropertyChanged("TransDateTime");
					this.OnTransDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TransCode
		{
			get
			{
				return this._TransCode;
			}
			set
			{
				if ((this._TransCode != value))
				{
					this.OnTransCodeChanging(value);
					this.SendPropertyChanging();
					this._TransCode = value;
					this.SendPropertyChanged("TransCode");
					this.OnTransCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CreditCardDetail")]
	public partial class CreditCardDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CreditCardDetailId;
		
		private int _RestaurantNo;
		
		private System.DateTime _TransDataTime;
		
		private string _ReferenceNo;
		
		private decimal _Amount;
		
		private string _CardType;
		
		private string _TransType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreditCardDetailIdChanging(int value);
    partial void OnCreditCardDetailIdChanged();
    partial void OnRestaurantNoChanging(int value);
    partial void OnRestaurantNoChanged();
    partial void OnTransDataTimeChanging(System.DateTime value);
    partial void OnTransDataTimeChanged();
    partial void OnReferenceNoChanging(string value);
    partial void OnReferenceNoChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnCardTypeChanging(string value);
    partial void OnCardTypeChanged();
    partial void OnTransTypeChanging(string value);
    partial void OnTransTypeChanged();
    #endregion
		
		public CreditCardDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CreditCardDetailId
		{
			get
			{
				return this._CreditCardDetailId;
			}
			set
			{
				if ((this._CreditCardDetailId != value))
				{
					this.OnCreditCardDetailIdChanging(value);
					this.SendPropertyChanging();
					this._CreditCardDetailId = value;
					this.SendPropertyChanged("CreditCardDetailId");
					this.OnCreditCardDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestaurantNo", DbType="Int NOT NULL")]
		public int RestaurantNo
		{
			get
			{
				return this._RestaurantNo;
			}
			set
			{
				if ((this._RestaurantNo != value))
				{
					this.OnRestaurantNoChanging(value);
					this.SendPropertyChanging();
					this._RestaurantNo = value;
					this.SendPropertyChanged("RestaurantNo");
					this.OnRestaurantNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDataTime", DbType="DateTime NOT NULL")]
		public System.DateTime TransDataTime
		{
			get
			{
				return this._TransDataTime;
			}
			set
			{
				if ((this._TransDataTime != value))
				{
					this.OnTransDataTimeChanging(value);
					this.SendPropertyChanging();
					this._TransDataTime = value;
					this.SendPropertyChanged("TransDataTime");
					this.OnTransDataTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReferenceNo
		{
			get
			{
				return this._ReferenceNo;
			}
			set
			{
				if ((this._ReferenceNo != value))
				{
					this.OnReferenceNoChanging(value);
					this.SendPropertyChanging();
					this._ReferenceNo = value;
					this.SendPropertyChanged("ReferenceNo");
					this.OnReferenceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CardType
		{
			get
			{
				return this._CardType;
			}
			set
			{
				if ((this._CardType != value))
				{
					this.OnCardTypeChanging(value);
					this.SendPropertyChanging();
					this._CardType = value;
					this.SendPropertyChanged("CardType");
					this.OnCardTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TransType
		{
			get
			{
				return this._TransType;
			}
			set
			{
				if ((this._TransType != value))
				{
					this.OnTransTypeChanging(value);
					this.SendPropertyChanging();
					this._TransType = value;
					this.SendPropertyChanged("TransType");
					this.OnTransTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FinFile")]
	public partial class FinFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FinFileId;
		
		private string _RestaurantNo;
		
		private string _FileName;
		
		private EntitySet<FinFileDetail> _FinFileDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFinFileIdChanging(int value);
    partial void OnFinFileIdChanged();
    partial void OnRestaurantNoChanging(string value);
    partial void OnRestaurantNoChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    #endregion
		
		public FinFile()
		{
			this._FinFileDetails = new EntitySet<FinFileDetail>(new Action<FinFileDetail>(this.attach_FinFileDetails), new Action<FinFileDetail>(this.detach_FinFileDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinFileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FinFileId
		{
			get
			{
				return this._FinFileId;
			}
			set
			{
				if ((this._FinFileId != value))
				{
					this.OnFinFileIdChanging(value);
					this.SendPropertyChanging();
					this._FinFileId = value;
					this.SendPropertyChanged("FinFileId");
					this.OnFinFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestaurantNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RestaurantNo
		{
			get
			{
				return this._RestaurantNo;
			}
			set
			{
				if ((this._RestaurantNo != value))
				{
					this.OnRestaurantNoChanging(value);
					this.SendPropertyChanging();
					this._RestaurantNo = value;
					this.SendPropertyChanged("RestaurantNo");
					this.OnRestaurantNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FinFile_FinFileDetail", Storage="_FinFileDetails", ThisKey="FinFileId", OtherKey="FinFileId")]
		public EntitySet<FinFileDetail> FinFileDetails
		{
			get
			{
				return this._FinFileDetails;
			}
			set
			{
				this._FinFileDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FinFileDetails(FinFileDetail entity)
		{
			this.SendPropertyChanging();
			entity.FinFile = this;
		}
		
		private void detach_FinFileDetails(FinFileDetail entity)
		{
			this.SendPropertyChanging();
			entity.FinFile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParentChildNumber")]
	public partial class ParentChildNumber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ParentChildNumberId;
		
		private string _Concept;
		
		private string _ParentNumber;
		
		private string _ParentDescription;
		
		private string _ChildNumber;
		
		private string _ChildDescription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnParentChildNumberIdChanging(int value);
    partial void OnParentChildNumberIdChanged();
    partial void OnConceptChanging(string value);
    partial void OnConceptChanged();
    partial void OnParentNumberChanging(string value);
    partial void OnParentNumberChanged();
    partial void OnParentDescriptionChanging(string value);
    partial void OnParentDescriptionChanged();
    partial void OnChildNumberChanging(string value);
    partial void OnChildNumberChanged();
    partial void OnChildDescriptionChanging(string value);
    partial void OnChildDescriptionChanged();
    #endregion
		
		public ParentChildNumber()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentChildNumberId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ParentChildNumberId
		{
			get
			{
				return this._ParentChildNumberId;
			}
			set
			{
				if ((this._ParentChildNumberId != value))
				{
					this.OnParentChildNumberIdChanging(value);
					this.SendPropertyChanging();
					this._ParentChildNumberId = value;
					this.SendPropertyChanged("ParentChildNumberId");
					this.OnParentChildNumberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concept", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Concept
		{
			get
			{
				return this._Concept;
			}
			set
			{
				if ((this._Concept != value))
				{
					this.OnConceptChanging(value);
					this.SendPropertyChanging();
					this._Concept = value;
					this.SendPropertyChanged("Concept");
					this.OnConceptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ParentNumber
		{
			get
			{
				return this._ParentNumber;
			}
			set
			{
				if ((this._ParentNumber != value))
				{
					this.OnParentNumberChanging(value);
					this.SendPropertyChanging();
					this._ParentNumber = value;
					this.SendPropertyChanged("ParentNumber");
					this.OnParentNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ParentDescription
		{
			get
			{
				return this._ParentDescription;
			}
			set
			{
				if ((this._ParentDescription != value))
				{
					this.OnParentDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ParentDescription = value;
					this.SendPropertyChanged("ParentDescription");
					this.OnParentDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChildNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChildNumber
		{
			get
			{
				return this._ChildNumber;
			}
			set
			{
				if ((this._ChildNumber != value))
				{
					this.OnChildNumberChanging(value);
					this.SendPropertyChanging();
					this._ChildNumber = value;
					this.SendPropertyChanged("ChildNumber");
					this.OnChildNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChildDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChildDescription
		{
			get
			{
				return this._ChildDescription;
			}
			set
			{
				if ((this._ChildDescription != value))
				{
					this.OnChildDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ChildDescription = value;
					this.SendPropertyChanged("ChildDescription");
					this.OnChildDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
