#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GiftCardProd")]
	public partial class GiftCardDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSvsHostRecon(SvsHostRecon instance);
    partial void UpdateSvsHostRecon(SvsHostRecon instance);
    partial void DeleteSvsHostRecon(SvsHostRecon instance);
    #endregion
		
		public GiftCardDataContext() : 
				base(global::TestOMatic2012.Properties.Settings.Default.GiftCardProdConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCardDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCardDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCardDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCardDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SvsHostRecon> SvsHostRecons
		{
			get
			{
				return this.GetTable<SvsHostRecon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SvsHostRecon")]
	public partial class SvsHostRecon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _SvsHostReconId;
		
		private decimal _FileId;
		
		private string _Card;
		
		private string _MerchantNumber;
		
		private string _DivisionNumber;
		
		private string _Unit;
		
		private string _TransCode;
		
		private char _DebitCredit;
		
		private System.DateTime _PosDate;
		
		private System.DateTime _HostDate;
		
		private decimal _PosRequestedAmount;
		
		private decimal _PosApprovedamount;
		
		private decimal _BaseRequestedamount;
		
		private decimal _BaseApprovedAmount;
		
		private string _SequenceNumber;
		
		private string _InvoiceNumber;
		
		private string _State;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _BusinessDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSvsHostReconIdChanging(decimal value);
    partial void OnSvsHostReconIdChanged();
    partial void OnFileIdChanging(decimal value);
    partial void OnFileIdChanged();
    partial void OnCardChanging(string value);
    partial void OnCardChanged();
    partial void OnMerchantNumberChanging(string value);
    partial void OnMerchantNumberChanged();
    partial void OnDivisionNumberChanging(string value);
    partial void OnDivisionNumberChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    partial void OnTransCodeChanging(string value);
    partial void OnTransCodeChanged();
    partial void OnDebitCreditChanging(char value);
    partial void OnDebitCreditChanged();
    partial void OnPosDateChanging(System.DateTime value);
    partial void OnPosDateChanged();
    partial void OnHostDateChanging(System.DateTime value);
    partial void OnHostDateChanged();
    partial void OnPosRequestedAmountChanging(decimal value);
    partial void OnPosRequestedAmountChanged();
    partial void OnPosApprovedamountChanging(decimal value);
    partial void OnPosApprovedamountChanged();
    partial void OnBaseRequestedamountChanging(decimal value);
    partial void OnBaseRequestedamountChanged();
    partial void OnBaseApprovedAmountChanging(decimal value);
    partial void OnBaseApprovedAmountChanged();
    partial void OnSequenceNumberChanging(string value);
    partial void OnSequenceNumberChanged();
    partial void OnInvoiceNumberChanging(string value);
    partial void OnInvoiceNumberChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnBusinessDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBusinessDateChanged();
    #endregion
		
		public SvsHostRecon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvsHostReconId", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal SvsHostReconId
		{
			get
			{
				return this._SvsHostReconId;
			}
			set
			{
				if ((this._SvsHostReconId != value))
				{
					this.OnSvsHostReconIdChanging(value);
					this.SendPropertyChanging();
					this._SvsHostReconId = value;
					this.SendPropertyChanged("SvsHostReconId");
					this.OnSvsHostReconIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileId", DbType="Decimal(18,0) NOT NULL")]
		public decimal FileId
		{
			get
			{
				return this._FileId;
			}
			set
			{
				if ((this._FileId != value))
				{
					this.OnFileIdChanging(value);
					this.SendPropertyChanging();
					this._FileId = value;
					this.SendPropertyChanged("FileId");
					this.OnFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card", DbType="NChar(19) NOT NULL", CanBeNull=false)]
		public string Card
		{
			get
			{
				return this._Card;
			}
			set
			{
				if ((this._Card != value))
				{
					this.OnCardChanging(value);
					this.SendPropertyChanging();
					this._Card = value;
					this.SendPropertyChanged("Card");
					this.OnCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerchantNumber", DbType="NChar(6) NOT NULL", CanBeNull=false)]
		public string MerchantNumber
		{
			get
			{
				return this._MerchantNumber;
			}
			set
			{
				if ((this._MerchantNumber != value))
				{
					this.OnMerchantNumberChanging(value);
					this.SendPropertyChanging();
					this._MerchantNumber = value;
					this.SendPropertyChanged("MerchantNumber");
					this.OnMerchantNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionNumber", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string DivisionNumber
		{
			get
			{
				return this._DivisionNumber;
			}
			set
			{
				if ((this._DivisionNumber != value))
				{
					this.OnDivisionNumberChanging(value);
					this.SendPropertyChanging();
					this._DivisionNumber = value;
					this.SendPropertyChanged("DivisionNumber");
					this.OnDivisionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransCode", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string TransCode
		{
			get
			{
				return this._TransCode;
			}
			set
			{
				if ((this._TransCode != value))
				{
					this.OnTransCodeChanging(value);
					this.SendPropertyChanging();
					this._TransCode = value;
					this.SendPropertyChanged("TransCode");
					this.OnTransCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebitCredit", DbType="NChar(1) NOT NULL")]
		public char DebitCredit
		{
			get
			{
				return this._DebitCredit;
			}
			set
			{
				if ((this._DebitCredit != value))
				{
					this.OnDebitCreditChanging(value);
					this.SendPropertyChanging();
					this._DebitCredit = value;
					this.SendPropertyChanged("DebitCredit");
					this.OnDebitCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosDate", DbType="DateTime NOT NULL")]
		public System.DateTime PosDate
		{
			get
			{
				return this._PosDate;
			}
			set
			{
				if ((this._PosDate != value))
				{
					this.OnPosDateChanging(value);
					this.SendPropertyChanging();
					this._PosDate = value;
					this.SendPropertyChanged("PosDate");
					this.OnPosDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostDate", DbType="DateTime NOT NULL")]
		public System.DateTime HostDate
		{
			get
			{
				return this._HostDate;
			}
			set
			{
				if ((this._HostDate != value))
				{
					this.OnHostDateChanging(value);
					this.SendPropertyChanging();
					this._HostDate = value;
					this.SendPropertyChanged("HostDate");
					this.OnHostDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosRequestedAmount", DbType="Decimal(18,2) NOT NULL")]
		public decimal PosRequestedAmount
		{
			get
			{
				return this._PosRequestedAmount;
			}
			set
			{
				if ((this._PosRequestedAmount != value))
				{
					this.OnPosRequestedAmountChanging(value);
					this.SendPropertyChanging();
					this._PosRequestedAmount = value;
					this.SendPropertyChanged("PosRequestedAmount");
					this.OnPosRequestedAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosApprovedamount", DbType="Decimal(18,2) NOT NULL")]
		public decimal PosApprovedamount
		{
			get
			{
				return this._PosApprovedamount;
			}
			set
			{
				if ((this._PosApprovedamount != value))
				{
					this.OnPosApprovedamountChanging(value);
					this.SendPropertyChanging();
					this._PosApprovedamount = value;
					this.SendPropertyChanged("PosApprovedamount");
					this.OnPosApprovedamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseRequestedamount", DbType="Decimal(18,2) NOT NULL")]
		public decimal BaseRequestedamount
		{
			get
			{
				return this._BaseRequestedamount;
			}
			set
			{
				if ((this._BaseRequestedamount != value))
				{
					this.OnBaseRequestedamountChanging(value);
					this.SendPropertyChanging();
					this._BaseRequestedamount = value;
					this.SendPropertyChanged("BaseRequestedamount");
					this.OnBaseRequestedamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseApprovedAmount", DbType="Decimal(18,2) NOT NULL")]
		public decimal BaseApprovedAmount
		{
			get
			{
				return this._BaseApprovedAmount;
			}
			set
			{
				if ((this._BaseApprovedAmount != value))
				{
					this.OnBaseApprovedAmountChanging(value);
					this.SendPropertyChanging();
					this._BaseApprovedAmount = value;
					this.SendPropertyChanged("BaseApprovedAmount");
					this.OnBaseApprovedAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequenceNumber", DbType="NChar(6) NOT NULL", CanBeNull=false)]
		public string SequenceNumber
		{
			get
			{
				return this._SequenceNumber;
			}
			set
			{
				if ((this._SequenceNumber != value))
				{
					this.OnSequenceNumberChanging(value);
					this.SendPropertyChanging();
					this._SequenceNumber = value;
					this.SendPropertyChanged("SequenceNumber");
					this.OnSequenceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this.OnInvoiceNumberChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNumber = value;
					this.SendPropertyChanged("InvoiceNumber");
					this.OnInvoiceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="Date")]
		public System.Nullable<System.DateTime> BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this.OnBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._BusinessDate = value;
					this.SendPropertyChanged("BusinessDate");
					this.OnBusinessDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
