<?xml version="1.0" encoding="utf-8"?><Database Name="HardeesRecipes" Class="HardeesRecipesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sql2012;Initial Catalog=HardeesRecipes;Integrated Security=True" SettingsObjectName="TestOMatic2012.Properties.Settings" SettingsPropertyName="HardeesRecipesConnectionString" Provider="System.Data.SqlClient" />
</Database>