<?xml version="1.0" encoding="utf-8"?><Database Name="HardeesRecipes" Class="HardeesRecipesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sql2012;Initial Catalog=HardeesRecipes;Integrated Security=True" SettingsObjectName="TestOMatic2012.Properties.Settings" SettingsPropertyName="HardeesRecipesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_Inv_ItemMaster" Member="TBL_Inv_ItemMasters">
    <Type Name="TBL_Inv_ItemMaster">
      <Column Name="tblItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="itemCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="itemGroupCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="statusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="storageCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="baseUnitOfMeasure" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="accountNo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="demandType" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="createBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="alternateUM" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="actualConversion" Type="System.Decimal" DbType="Decimal(9,3)" CanBeNull="true" />
      <Column Name="idealConversion" Type="System.Decimal" DbType="Decimal(9,3)" CanBeNull="true" />
      <Column Name="alphaSearchCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="countFreq" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="lastChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastChangeBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isReciped" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>