#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HardeesRecipes")]
	public partial class HardeesRecipesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_Inv_ItemMaster(TBL_Inv_ItemMaster instance);
    partial void UpdateTBL_Inv_ItemMaster(TBL_Inv_ItemMaster instance);
    partial void DeleteTBL_Inv_ItemMaster(TBL_Inv_ItemMaster instance);
    #endregion
		
		public HardeesRecipesDataContext() : 
				base(global::TestOMatic2012.Properties.Settings.Default.HardeesRecipesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HardeesRecipesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HardeesRecipesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HardeesRecipesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HardeesRecipesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_Inv_ItemMaster> TBL_Inv_ItemMasters
		{
			get
			{
				return this.GetTable<TBL_Inv_ItemMaster>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Inv_ItemMaster")]
	public partial class TBL_Inv_ItemMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tblItemId;
		
		private string _itemCode;
		
		private string _description;
		
		private string _itemGroupCode;
		
		private System.Nullable<int> _statusCode;
		
		private string _storageCode;
		
		private string _baseUnitOfMeasure;
		
		private string _accountNo;
		
		private string _demandType;
		
		private System.Nullable<System.DateTime> _createDate;
		
		private string _createBy;
		
		private string _alternateUM;
		
		private System.Nullable<decimal> _actualConversion;
		
		private System.Nullable<decimal> _idealConversion;
		
		private string _alphaSearchCode;
		
		private string _countFreq;
		
		private System.Nullable<System.DateTime> _lastChangeDate;
		
		private string _lastChangeBy;
		
		private System.Nullable<bool> _isReciped;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntblItemIdChanging(int value);
    partial void OntblItemIdChanged();
    partial void OnitemCodeChanging(string value);
    partial void OnitemCodeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnitemGroupCodeChanging(string value);
    partial void OnitemGroupCodeChanged();
    partial void OnstatusCodeChanging(System.Nullable<int> value);
    partial void OnstatusCodeChanged();
    partial void OnstorageCodeChanging(string value);
    partial void OnstorageCodeChanged();
    partial void OnbaseUnitOfMeasureChanging(string value);
    partial void OnbaseUnitOfMeasureChanged();
    partial void OnaccountNoChanging(string value);
    partial void OnaccountNoChanged();
    partial void OndemandTypeChanging(string value);
    partial void OndemandTypeChanged();
    partial void OncreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateChanged();
    partial void OncreateByChanging(string value);
    partial void OncreateByChanged();
    partial void OnalternateUMChanging(string value);
    partial void OnalternateUMChanged();
    partial void OnactualConversionChanging(System.Nullable<decimal> value);
    partial void OnactualConversionChanged();
    partial void OnidealConversionChanging(System.Nullable<decimal> value);
    partial void OnidealConversionChanged();
    partial void OnalphaSearchCodeChanging(string value);
    partial void OnalphaSearchCodeChanged();
    partial void OncountFreqChanging(string value);
    partial void OncountFreqChanged();
    partial void OnlastChangeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastChangeDateChanged();
    partial void OnlastChangeByChanging(string value);
    partial void OnlastChangeByChanged();
    partial void OnisRecipedChanging(System.Nullable<bool> value);
    partial void OnisRecipedChanged();
    #endregion
		
		public TBL_Inv_ItemMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tblItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tblItemId
		{
			get
			{
				return this._tblItemId;
			}
			set
			{
				if ((this._tblItemId != value))
				{
					this.OntblItemIdChanging(value);
					this.SendPropertyChanging();
					this._tblItemId = value;
					this.SendPropertyChanged("tblItemId");
					this.OntblItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string itemCode
		{
			get
			{
				return this._itemCode;
			}
			set
			{
				if ((this._itemCode != value))
				{
					this.OnitemCodeChanging(value);
					this.SendPropertyChanging();
					this._itemCode = value;
					this.SendPropertyChanged("itemCode");
					this.OnitemCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemGroupCode", DbType="VarChar(5)")]
		public string itemGroupCode
		{
			get
			{
				return this._itemGroupCode;
			}
			set
			{
				if ((this._itemGroupCode != value))
				{
					this.OnitemGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._itemGroupCode = value;
					this.SendPropertyChanged("itemGroupCode");
					this.OnitemGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusCode", DbType="Int")]
		public System.Nullable<int> statusCode
		{
			get
			{
				return this._statusCode;
			}
			set
			{
				if ((this._statusCode != value))
				{
					this.OnstatusCodeChanging(value);
					this.SendPropertyChanging();
					this._statusCode = value;
					this.SendPropertyChanged("statusCode");
					this.OnstatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storageCode", DbType="VarChar(5)")]
		public string storageCode
		{
			get
			{
				return this._storageCode;
			}
			set
			{
				if ((this._storageCode != value))
				{
					this.OnstorageCodeChanging(value);
					this.SendPropertyChanging();
					this._storageCode = value;
					this.SendPropertyChanged("storageCode");
					this.OnstorageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baseUnitOfMeasure", DbType="VarChar(5)")]
		public string baseUnitOfMeasure
		{
			get
			{
				return this._baseUnitOfMeasure;
			}
			set
			{
				if ((this._baseUnitOfMeasure != value))
				{
					this.OnbaseUnitOfMeasureChanging(value);
					this.SendPropertyChanging();
					this._baseUnitOfMeasure = value;
					this.SendPropertyChanged("baseUnitOfMeasure");
					this.OnbaseUnitOfMeasureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountNo", DbType="VarChar(10)")]
		public string accountNo
		{
			get
			{
				return this._accountNo;
			}
			set
			{
				if ((this._accountNo != value))
				{
					this.OnaccountNoChanging(value);
					this.SendPropertyChanging();
					this._accountNo = value;
					this.SendPropertyChanged("accountNo");
					this.OnaccountNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_demandType", DbType="VarChar(2)")]
		public string demandType
		{
			get
			{
				return this._demandType;
			}
			set
			{
				if ((this._demandType != value))
				{
					this.OndemandTypeChanging(value);
					this.SendPropertyChanging();
					this._demandType = value;
					this.SendPropertyChanged("demandType");
					this.OndemandTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createBy", DbType="VarChar(50)")]
		public string createBy
		{
			get
			{
				return this._createBy;
			}
			set
			{
				if ((this._createBy != value))
				{
					this.OncreateByChanging(value);
					this.SendPropertyChanging();
					this._createBy = value;
					this.SendPropertyChanged("createBy");
					this.OncreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alternateUM", DbType="VarChar(5)")]
		public string alternateUM
		{
			get
			{
				return this._alternateUM;
			}
			set
			{
				if ((this._alternateUM != value))
				{
					this.OnalternateUMChanging(value);
					this.SendPropertyChanging();
					this._alternateUM = value;
					this.SendPropertyChanged("alternateUM");
					this.OnalternateUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualConversion", DbType="Decimal(9,3)")]
		public System.Nullable<decimal> actualConversion
		{
			get
			{
				return this._actualConversion;
			}
			set
			{
				if ((this._actualConversion != value))
				{
					this.OnactualConversionChanging(value);
					this.SendPropertyChanging();
					this._actualConversion = value;
					this.SendPropertyChanged("actualConversion");
					this.OnactualConversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idealConversion", DbType="Decimal(9,3)")]
		public System.Nullable<decimal> idealConversion
		{
			get
			{
				return this._idealConversion;
			}
			set
			{
				if ((this._idealConversion != value))
				{
					this.OnidealConversionChanging(value);
					this.SendPropertyChanging();
					this._idealConversion = value;
					this.SendPropertyChanged("idealConversion");
					this.OnidealConversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alphaSearchCode", DbType="VarChar(50)")]
		public string alphaSearchCode
		{
			get
			{
				return this._alphaSearchCode;
			}
			set
			{
				if ((this._alphaSearchCode != value))
				{
					this.OnalphaSearchCodeChanging(value);
					this.SendPropertyChanging();
					this._alphaSearchCode = value;
					this.SendPropertyChanged("alphaSearchCode");
					this.OnalphaSearchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countFreq", DbType="VarChar(2)")]
		public string countFreq
		{
			get
			{
				return this._countFreq;
			}
			set
			{
				if ((this._countFreq != value))
				{
					this.OncountFreqChanging(value);
					this.SendPropertyChanging();
					this._countFreq = value;
					this.SendPropertyChanged("countFreq");
					this.OncountFreqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastChangeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastChangeDate
		{
			get
			{
				return this._lastChangeDate;
			}
			set
			{
				if ((this._lastChangeDate != value))
				{
					this.OnlastChangeDateChanging(value);
					this.SendPropertyChanging();
					this._lastChangeDate = value;
					this.SendPropertyChanged("lastChangeDate");
					this.OnlastChangeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastChangeBy", DbType="VarChar(50)")]
		public string lastChangeBy
		{
			get
			{
				return this._lastChangeBy;
			}
			set
			{
				if ((this._lastChangeBy != value))
				{
					this.OnlastChangeByChanging(value);
					this.SendPropertyChanging();
					this._lastChangeBy = value;
					this.SendPropertyChanged("lastChangeBy");
					this.OnlastChangeByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isReciped", DbType="Bit")]
		public System.Nullable<bool> isReciped
		{
			get
			{
				return this._isReciped;
			}
			set
			{
				if ((this._isReciped != value))
				{
					this.OnisRecipedChanging(value);
					this.SendPropertyChanging();
					this._isReciped = value;
					this.SendPropertyChanged("isReciped");
					this.OnisRecipedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
