#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HFSDB")]
	public partial class HFSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalendar(Calendar instance);
    partial void UpdateCalendar(Calendar instance);
    partial void DeleteCalendar(Calendar instance);
    partial void InsertStoreInfo(StoreInfo instance);
    partial void UpdateStoreInfo(StoreInfo instance);
    partial void DeleteStoreInfo(StoreInfo instance);
    #endregion
		
		public HFSDBDataContext() : 
				base(global::TestOMatic2012.Properties.Settings.Default.HFSDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Calendar> Calendars
		{
			get
			{
				return this.GetTable<Calendar>();
			}
		}
		
		public System.Data.Linq.Table<StoreInfo> StoreInfos
		{
			get
			{
				return this.GetTable<StoreInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Config.Calendar")]
	public partial class Calendar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimeId;
		
		private System.DateTime _CalDate;
		
		private System.Nullable<System.DateTime> _CalWeekEndDate;
		
		private System.Nullable<int> _FsclPerId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeIdChanging(int value);
    partial void OnTimeIdChanged();
    partial void OnCalDateChanging(System.DateTime value);
    partial void OnCalDateChanged();
    partial void OnCalWeekEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCalWeekEndDateChanged();
    partial void OnFsclPerIdChanging(System.Nullable<int> value);
    partial void OnFsclPerIdChanged();
    #endregion
		
		public Calendar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TimeId
		{
			get
			{
				return this._TimeId;
			}
			set
			{
				if ((this._TimeId != value))
				{
					this.OnTimeIdChanging(value);
					this.SendPropertyChanging();
					this._TimeId = value;
					this.SendPropertyChanged("TimeId");
					this.OnTimeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalDate", DbType="DateTime NOT NULL")]
		public System.DateTime CalDate
		{
			get
			{
				return this._CalDate;
			}
			set
			{
				if ((this._CalDate != value))
				{
					this.OnCalDateChanging(value);
					this.SendPropertyChanging();
					this._CalDate = value;
					this.SendPropertyChanged("CalDate");
					this.OnCalDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalWeekEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CalWeekEndDate
		{
			get
			{
				return this._CalWeekEndDate;
			}
			set
			{
				if ((this._CalWeekEndDate != value))
				{
					this.OnCalWeekEndDateChanging(value);
					this.SendPropertyChanging();
					this._CalWeekEndDate = value;
					this.SendPropertyChanged("CalWeekEndDate");
					this.OnCalWeekEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FsclPerId", DbType="Int")]
		public System.Nullable<int> FsclPerId
		{
			get
			{
				return this._FsclPerId;
			}
			set
			{
				if ((this._FsclPerId != value))
				{
					this.OnFsclPerIdChanging(value);
					this.SendPropertyChanging();
					this._FsclPerId = value;
					this.SendPropertyChanged("FsclPerId");
					this.OnFsclPerIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Config.StoreInfo")]
	public partial class StoreInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CompanyName;
		
		private string _StoreName;
		
		private string _UnitNumber;
		
		private string _Phone;
		
		private string _Street1;
		
		private string _Street2;
		
		private string _City;
		
		private string _State;
		
		private string _ZipCode;
		
		private System.Nullable<decimal> _ClearAmount;
		
		private System.Nullable<int> _BreakTimeLimit;
		
		private System.Nullable<int> _DayStartTime;
		
		private System.Nullable<short> _WeekStartDaySystem;
		
		private System.Nullable<short> _WeekStartDayPayroll;
		
		private System.Nullable<System.DateTime> _BusinessDate;
		
		private System.Nullable<short> _ConceptId;
		
		private System.Data.Linq.Binary _RowNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnStreet1Changing(string value);
    partial void OnStreet1Changed();
    partial void OnStreet2Changing(string value);
    partial void OnStreet2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnClearAmountChanging(System.Nullable<decimal> value);
    partial void OnClearAmountChanged();
    partial void OnBreakTimeLimitChanging(System.Nullable<int> value);
    partial void OnBreakTimeLimitChanged();
    partial void OnDayStartTimeChanging(System.Nullable<int> value);
    partial void OnDayStartTimeChanged();
    partial void OnWeekStartDaySystemChanging(System.Nullable<short> value);
    partial void OnWeekStartDaySystemChanged();
    partial void OnWeekStartDayPayrollChanging(System.Nullable<short> value);
    partial void OnWeekStartDayPayrollChanged();
    partial void OnBusinessDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBusinessDateChanged();
    partial void OnConceptIdChanging(System.Nullable<short> value);
    partial void OnConceptIdChanged();
    partial void OnRowNumberChanging(System.Data.Linq.Binary value);
    partial void OnRowNumberChanged();
    #endregion
		
		public StoreInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street1", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Street1
		{
			get
			{
				return this._Street1;
			}
			set
			{
				if ((this._Street1 != value))
				{
					this.OnStreet1Changing(value);
					this.SendPropertyChanging();
					this._Street1 = value;
					this.SendPropertyChanged("Street1");
					this.OnStreet1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street2", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Street2
		{
			get
			{
				return this._Street2;
			}
			set
			{
				if ((this._Street2 != value))
				{
					this.OnStreet2Changing(value);
					this.SendPropertyChanging();
					this._Street2 = value;
					this.SendPropertyChanged("Street2");
					this.OnStreet2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NChar(2)", UpdateCheck=UpdateCheck.Never)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClearAmount", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> ClearAmount
		{
			get
			{
				return this._ClearAmount;
			}
			set
			{
				if ((this._ClearAmount != value))
				{
					this.OnClearAmountChanging(value);
					this.SendPropertyChanging();
					this._ClearAmount = value;
					this.SendPropertyChanged("ClearAmount");
					this.OnClearAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BreakTimeLimit", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> BreakTimeLimit
		{
			get
			{
				return this._BreakTimeLimit;
			}
			set
			{
				if ((this._BreakTimeLimit != value))
				{
					this.OnBreakTimeLimitChanging(value);
					this.SendPropertyChanging();
					this._BreakTimeLimit = value;
					this.SendPropertyChanged("BreakTimeLimit");
					this.OnBreakTimeLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayStartTime", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DayStartTime
		{
			get
			{
				return this._DayStartTime;
			}
			set
			{
				if ((this._DayStartTime != value))
				{
					this.OnDayStartTimeChanging(value);
					this.SendPropertyChanging();
					this._DayStartTime = value;
					this.SendPropertyChanged("DayStartTime");
					this.OnDayStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekStartDaySystem", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> WeekStartDaySystem
		{
			get
			{
				return this._WeekStartDaySystem;
			}
			set
			{
				if ((this._WeekStartDaySystem != value))
				{
					this.OnWeekStartDaySystemChanging(value);
					this.SendPropertyChanging();
					this._WeekStartDaySystem = value;
					this.SendPropertyChanged("WeekStartDaySystem");
					this.OnWeekStartDaySystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekStartDayPayroll", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> WeekStartDayPayroll
		{
			get
			{
				return this._WeekStartDayPayroll;
			}
			set
			{
				if ((this._WeekStartDayPayroll != value))
				{
					this.OnWeekStartDayPayrollChanging(value);
					this.SendPropertyChanging();
					this._WeekStartDayPayroll = value;
					this.SendPropertyChanged("WeekStartDayPayroll");
					this.OnWeekStartDayPayrollChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this.OnBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._BusinessDate = value;
					this.SendPropertyChanged("BusinessDate");
					this.OnBusinessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConceptId", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> ConceptId
		{
			get
			{
				return this._ConceptId;
			}
			set
			{
				if ((this._ConceptId != value))
				{
					this.OnConceptIdChanging(value);
					this.SendPropertyChanging();
					this._ConceptId = value;
					this.SendPropertyChanged("ConceptId");
					this.OnConceptIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this.OnRowNumberChanging(value);
					this.SendPropertyChanging();
					this._RowNumber = value;
					this.SendPropertyChanged("RowNumber");
					this.OnRowNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
