#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HFSDB")]
	public partial class HFSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalendar(Calendar instance);
    partial void UpdateCalendar(Calendar instance);
    partial void DeleteCalendar(Calendar instance);
    #endregion
		
		public HFSDBDataContext() : 
				base(global::TestOMatic2012.Properties.Settings.Default.HFSDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HFSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Calendar> Calendars
		{
			get
			{
				return this.GetTable<Calendar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Config.Calendar")]
	public partial class Calendar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimeId;
		
		private System.DateTime _CalDate;
		
		private System.Nullable<System.DateTime> _CalWeekEndDate;
		
		private System.Nullable<int> _FsclPerId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeIdChanging(int value);
    partial void OnTimeIdChanged();
    partial void OnCalDateChanging(System.DateTime value);
    partial void OnCalDateChanged();
    partial void OnCalWeekEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCalWeekEndDateChanged();
    partial void OnFsclPerIdChanging(System.Nullable<int> value);
    partial void OnFsclPerIdChanged();
    #endregion
		
		public Calendar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TimeId
		{
			get
			{
				return this._TimeId;
			}
			set
			{
				if ((this._TimeId != value))
				{
					this.OnTimeIdChanging(value);
					this.SendPropertyChanging();
					this._TimeId = value;
					this.SendPropertyChanged("TimeId");
					this.OnTimeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalDate", DbType="DateTime NOT NULL")]
		public System.DateTime CalDate
		{
			get
			{
				return this._CalDate;
			}
			set
			{
				if ((this._CalDate != value))
				{
					this.OnCalDateChanging(value);
					this.SendPropertyChanging();
					this._CalDate = value;
					this.SendPropertyChanged("CalDate");
					this.OnCalDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalWeekEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CalWeekEndDate
		{
			get
			{
				return this._CalWeekEndDate;
			}
			set
			{
				if ((this._CalWeekEndDate != value))
				{
					this.OnCalWeekEndDateChanging(value);
					this.SendPropertyChanging();
					this._CalWeekEndDate = value;
					this.SendPropertyChanged("CalWeekEndDate");
					this.OnCalWeekEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FsclPerId", DbType="Int")]
		public System.Nullable<int> FsclPerId
		{
			get
			{
				return this._FsclPerId;
			}
			set
			{
				if ((this._FsclPerId != value))
				{
					this.OnFsclPerIdChanging(value);
					this.SendPropertyChanging();
					this._FsclPerId = value;
					this.SendPropertyChanged("FsclPerId");
					this.OnFsclPerIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
