<?xml version="1.0" encoding="utf-8"?><Database Name="INFO2000" Class="INFO2000DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=INFO2000;Integrated Security=True" SettingsObjectName="TestOMatic2012.Properties.Settings" SettingsPropertyName="INFO2000ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.deposit_dtl_fact" Member="deposit_dtl_facts">
    <Type Name="deposit_dtl_fact">
      <Column Name="deposit_dtl_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="deposit_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="POS_fact_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="System_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Restaurant_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cal_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Deposit_amt" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="create_by" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="last_chg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_chg_by" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="deposit_dim_deposit_dtl_fact" Member="deposit_dim" ThisKey="deposit_id" OtherKey="deposit_id" Type="deposit_dim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.deposit_dim" Member="deposit_dims">
    <Type Name="deposit_dim">
      <Column Name="deposit_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="System_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Restaurant_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deposit_type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="deposit_descr" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="eff_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="term_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deposit_group" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="deposit_category" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="deposit_dim_deposit_dtl_fact" Member="deposit_dtl_facts" ThisKey="deposit_id" OtherKey="deposit_id" Type="deposit_dtl_fact" />
    </Type>
  </Table>
</Database>