<?xml version="1.0" encoding="utf-8"?><Database Name="INFO2000" Class="INFO2000DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sql2012;Initial Catalog=INFO2000;Integrated Security=True" SettingsObjectName="TestOMatic2012.Properties.Settings" SettingsPropertyName="INFO2000ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.deposit_dtl_fact" Member="deposit_dtl_facts">
    <Type Name="deposit_dtl_fact">
      <Column Name="deposit_dtl_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="deposit_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="POS_fact_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="System_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Restaurant_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cal_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Deposit_amt" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="create_by" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="last_chg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_chg_by" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="deposit_dim_deposit_dtl_fact" Member="deposit_dim" ThisKey="deposit_id" OtherKey="deposit_id" Type="deposit_dim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.deposit_dim" Member="deposit_dims">
    <Type Name="deposit_dim">
      <Column Name="deposit_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="System_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Restaurant_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deposit_type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="deposit_descr" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="eff_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="term_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deposit_group" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="deposit_category" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="deposit_dim_deposit_dtl_fact" Member="deposit_dtl_facts" ThisKey="deposit_id" OtherKey="deposit_id" Type="deposit_dtl_fact" />
    </Type>
  </Table>
  <Table Name="dbo.IR_Total_Net_Sales" Member="IR_Total_Net_Sales">
    <Type Name="IR_Total_Net_Sale">
      <Column Name="IR_Unit_Number" Type="System.String" DbType="VarChar(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IR_Sales_Date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Total_Net_Sales_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Net_Sales_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Net_Sales_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Trans_Here" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Trans_Togo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Trans_Drive" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_NF_Sales_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_NF_Sales_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_NF_Sales_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Voids_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Voids_Cnt" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Free_Sales_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Free_Sales_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Free_Sales_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Free_Trans_Here" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Free_Trans_Togo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Free_Trans_Drive" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Cleared_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Cleared_Cnt" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Paid_I_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Paid_O_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cents_Off_Here_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cents_Off_Here_Cnt" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Cents_Off_Togo_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cents_Off_Togo_Cnt" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Cents_Off_Drive_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cents_Off_Drive_Cnt" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Nrs_Total" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="Total_Taxable_Sales" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Tax_Collected" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Opn_Promo_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Opn_Promo_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Opn_Promo_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Opn_Trans_Here" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Opn_Trans_Togo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Opn_Trans_Drive" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Cpn_Promo_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Cpn_Promo_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Cpn_Promo_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_Cpn_Trans_Here" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Cpn_Trans_Togo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Cpn_Trans_Drive" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_A_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_A_Here" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_B_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_B_Here" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_C_Here" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_C_Here" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_A_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_A_Togo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_B_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_B_Togo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_C_Togo" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_C_Togo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_A_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_A_Drive" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_B_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_B_Drive" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Amt_C_Drive" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Cust_Dis_Cnt_C_Drive" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Emp_Dis_Amt_A" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Emp_Dis_Cnt_A" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Emp_Dis_Amt_B" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Emp_Dis_Cnt_B" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Emp_Dis_Amt_C" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Emp_Dis_Cnt_C" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Mgr_Dis_Amt_A" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Mgr_Dis_Cnt_A" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Mgr_Dis_Amt_B" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Mgr_Dis_Cnt_B" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Tot_Mgr_Dis_Amt_C" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Tot_Mgr_Dis_Cnt_C" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Assoc_Menu_Id_1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Assoc_Trans_Cnt_1" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Assoc_Type_1" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Assoc_Menu_Id_2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Assoc_Trans_Cnt_2" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Assoc_Type_2" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Assoc_Menu_Id_3" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Assoc_Trans_Cnt_3" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Assoc_Type_3" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Cash_Deposits_1" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cash_Deposits_2" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cash_Deposits_3" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cash_Deposits_4" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cash_Deposits_5" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Cash_Deposits_6" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_giftcard_sales_amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Total_giftcard_sales_cnt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="ATM" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Checks" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Visa_Master_Card" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="American_Express" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="FirstCard" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Discover" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="total_gftcrt_sls_amt" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="total_gftcrt_sls_cnt" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="process_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="process_flag" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Total_Scanned_Cpn_Cnt" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Total_Scanned_Cpn_Amt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>