#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOMatic2012
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TimeFileAnalysis")]
	public partial class TimeFileAnalysisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTimeCardRecord(TimeCardRecord instance);
    partial void UpdateTimeCardRecord(TimeCardRecord instance);
    partial void DeleteTimeCardRecord(TimeCardRecord instance);
    partial void InsertTimeCardWeekEndDate(TimeCardWeekEndDate instance);
    partial void UpdateTimeCardWeekEndDate(TimeCardWeekEndDate instance);
    partial void DeleteTimeCardWeekEndDate(TimeCardWeekEndDate instance);
    partial void InsertTimeCardDetail(TimeCardDetail instance);
    partial void UpdateTimeCardDetail(TimeCardDetail instance);
    partial void DeleteTimeCardDetail(TimeCardDetail instance);
    partial void InsertTimeCardTotal(TimeCardTotal instance);
    partial void UpdateTimeCardTotal(TimeCardTotal instance);
    partial void DeleteTimeCardTotal(TimeCardTotal instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public TimeFileAnalysisDataContext() : 
				base(global::TestOMatic2012.Properties.Settings.Default.TimeFileAnalysisConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TimeFileAnalysisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimeFileAnalysisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimeFileAnalysisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimeFileAnalysisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TimeCardRecord> TimeCardRecords
		{
			get
			{
				return this.GetTable<TimeCardRecord>();
			}
		}
		
		public System.Data.Linq.Table<TimeCardWeekEndDate> TimeCardWeekEndDates
		{
			get
			{
				return this.GetTable<TimeCardWeekEndDate>();
			}
		}
		
		public System.Data.Linq.Table<TimeCardDetail> TimeCardDetails
		{
			get
			{
				return this.GetTable<TimeCardDetail>();
			}
		}
		
		public System.Data.Linq.Table<TimeCardTotal> TimeCardTotals
		{
			get
			{
				return this.GetTable<TimeCardTotal>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeCardRecord")]
	public partial class TimeCardRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimeCardRecordId;
		
		private string _UnitNumber;
		
		private string _EmployeeName;
		
		private string _EmployeeJobCode;
		
		private string _SSN;
		
		private System.DateTime _WeekEndDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeCardRecordIdChanging(int value);
    partial void OnTimeCardRecordIdChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnEmployeeJobCodeChanging(string value);
    partial void OnEmployeeJobCodeChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnWeekEndDateChanging(System.DateTime value);
    partial void OnWeekEndDateChanged();
    #endregion
		
		public TimeCardRecord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCardRecordId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TimeCardRecordId
		{
			get
			{
				return this._TimeCardRecordId;
			}
			set
			{
				if ((this._TimeCardRecordId != value))
				{
					this.OnTimeCardRecordIdChanging(value);
					this.SendPropertyChanging();
					this._TimeCardRecordId = value;
					this.SendPropertyChanged("TimeCardRecordId");
					this.OnTimeCardRecordIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this.OnEmployeeNameChanging(value);
					this.SendPropertyChanging();
					this._EmployeeName = value;
					this.SendPropertyChanged("EmployeeName");
					this.OnEmployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeJobCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmployeeJobCode
		{
			get
			{
				return this._EmployeeJobCode;
			}
			set
			{
				if ((this._EmployeeJobCode != value))
				{
					this.OnEmployeeJobCodeChanging(value);
					this.SendPropertyChanging();
					this._EmployeeJobCode = value;
					this.SendPropertyChanged("EmployeeJobCode");
					this.OnEmployeeJobCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekEndDate", DbType="DateTime NOT NULL")]
		public System.DateTime WeekEndDate
		{
			get
			{
				return this._WeekEndDate;
			}
			set
			{
				if ((this._WeekEndDate != value))
				{
					this.OnWeekEndDateChanging(value);
					this.SendPropertyChanging();
					this._WeekEndDate = value;
					this.SendPropertyChanged("WeekEndDate");
					this.OnWeekEndDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeCardWeekEndDate")]
	public partial class TimeCardWeekEndDate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WeekEndDateId;
		
		private System.DateTime _WeekEndDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWeekEndDateIdChanging(int value);
    partial void OnWeekEndDateIdChanged();
    partial void OnWeekEndDateChanging(System.DateTime value);
    partial void OnWeekEndDateChanged();
    #endregion
		
		public TimeCardWeekEndDate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekEndDateId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WeekEndDateId
		{
			get
			{
				return this._WeekEndDateId;
			}
			set
			{
				if ((this._WeekEndDateId != value))
				{
					this.OnWeekEndDateIdChanging(value);
					this.SendPropertyChanging();
					this._WeekEndDateId = value;
					this.SendPropertyChanged("WeekEndDateId");
					this.OnWeekEndDateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekEndDate", DbType="DateTime NOT NULL")]
		public System.DateTime WeekEndDate
		{
			get
			{
				return this._WeekEndDate;
			}
			set
			{
				if ((this._WeekEndDate != value))
				{
					this.OnWeekEndDateChanging(value);
					this.SendPropertyChanging();
					this._WeekEndDate = value;
					this.SendPropertyChanged("WeekEndDate");
					this.OnWeekEndDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeCardDetail")]
	public partial class TimeCardDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimeCardDetailId;
		
		private int _TimeCardRecordId;
		
		private System.DateTime _BusinessDate;
		
		private string _DayOfWeek;
		
		private decimal _ClockIn;
		
		private decimal _ClockOut;
		
		private decimal _ElapsedTime;
		
		private string _ShiftStatusCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeCardDetailIdChanging(int value);
    partial void OnTimeCardDetailIdChanged();
    partial void OnTimeCardRecordIdChanging(int value);
    partial void OnTimeCardRecordIdChanged();
    partial void OnBusinessDateChanging(System.DateTime value);
    partial void OnBusinessDateChanged();
    partial void OnDayOfWeekChanging(string value);
    partial void OnDayOfWeekChanged();
    partial void OnClockInChanging(decimal value);
    partial void OnClockInChanged();
    partial void OnClockOutChanging(decimal value);
    partial void OnClockOutChanged();
    partial void OnElapsedTimeChanging(decimal value);
    partial void OnElapsedTimeChanged();
    partial void OnShiftStatusCodeChanging(string value);
    partial void OnShiftStatusCodeChanged();
    #endregion
		
		public TimeCardDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCardDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TimeCardDetailId
		{
			get
			{
				return this._TimeCardDetailId;
			}
			set
			{
				if ((this._TimeCardDetailId != value))
				{
					this.OnTimeCardDetailIdChanging(value);
					this.SendPropertyChanging();
					this._TimeCardDetailId = value;
					this.SendPropertyChanged("TimeCardDetailId");
					this.OnTimeCardDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCardRecordId", DbType="Int NOT NULL")]
		public int TimeCardRecordId
		{
			get
			{
				return this._TimeCardRecordId;
			}
			set
			{
				if ((this._TimeCardRecordId != value))
				{
					this.OnTimeCardRecordIdChanging(value);
					this.SendPropertyChanging();
					this._TimeCardRecordId = value;
					this.SendPropertyChanged("TimeCardRecordId");
					this.OnTimeCardRecordIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="DateTime NOT NULL")]
		public System.DateTime BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this.OnBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._BusinessDate = value;
					this.SendPropertyChanged("BusinessDate");
					this.OnBusinessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayOfWeek", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DayOfWeek
		{
			get
			{
				return this._DayOfWeek;
			}
			set
			{
				if ((this._DayOfWeek != value))
				{
					this.OnDayOfWeekChanging(value);
					this.SendPropertyChanging();
					this._DayOfWeek = value;
					this.SendPropertyChanged("DayOfWeek");
					this.OnDayOfWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClockIn", DbType="Decimal(18,6) NOT NULL")]
		public decimal ClockIn
		{
			get
			{
				return this._ClockIn;
			}
			set
			{
				if ((this._ClockIn != value))
				{
					this.OnClockInChanging(value);
					this.SendPropertyChanging();
					this._ClockIn = value;
					this.SendPropertyChanged("ClockIn");
					this.OnClockInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClockOut", DbType="Decimal(18,6) NOT NULL")]
		public decimal ClockOut
		{
			get
			{
				return this._ClockOut;
			}
			set
			{
				if ((this._ClockOut != value))
				{
					this.OnClockOutChanging(value);
					this.SendPropertyChanging();
					this._ClockOut = value;
					this.SendPropertyChanged("ClockOut");
					this.OnClockOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTime", DbType="Decimal(18,6) NOT NULL")]
		public decimal ElapsedTime
		{
			get
			{
				return this._ElapsedTime;
			}
			set
			{
				if ((this._ElapsedTime != value))
				{
					this.OnElapsedTimeChanging(value);
					this.SendPropertyChanging();
					this._ElapsedTime = value;
					this.SendPropertyChanged("ElapsedTime");
					this.OnElapsedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftStatusCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShiftStatusCode
		{
			get
			{
				return this._ShiftStatusCode;
			}
			set
			{
				if ((this._ShiftStatusCode != value))
				{
					this.OnShiftStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._ShiftStatusCode = value;
					this.SendPropertyChanged("ShiftStatusCode");
					this.OnShiftStatusCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeCardTotal")]
	public partial class TimeCardTotal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimeCardTotalId;
		
		private int _TimeCardRecordId;
		
		private int _EmployeeId;
		
		private decimal _RegularHours;
		
		private decimal _OvertimeHours;
		
		private decimal _VacationHours;
		
		private decimal _TotalHours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeCardTotalIdChanging(int value);
    partial void OnTimeCardTotalIdChanged();
    partial void OnTimeCardRecordIdChanging(int value);
    partial void OnTimeCardRecordIdChanged();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnRegularHoursChanging(decimal value);
    partial void OnRegularHoursChanged();
    partial void OnOvertimeHoursChanging(decimal value);
    partial void OnOvertimeHoursChanged();
    partial void OnVacationHoursChanging(decimal value);
    partial void OnVacationHoursChanged();
    partial void OnTotalHoursChanging(decimal value);
    partial void OnTotalHoursChanged();
    #endregion
		
		public TimeCardTotal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCardTotalId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TimeCardTotalId
		{
			get
			{
				return this._TimeCardTotalId;
			}
			set
			{
				if ((this._TimeCardTotalId != value))
				{
					this.OnTimeCardTotalIdChanging(value);
					this.SendPropertyChanging();
					this._TimeCardTotalId = value;
					this.SendPropertyChanged("TimeCardTotalId");
					this.OnTimeCardTotalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCardRecordId", DbType="Int NOT NULL")]
		public int TimeCardRecordId
		{
			get
			{
				return this._TimeCardRecordId;
			}
			set
			{
				if ((this._TimeCardRecordId != value))
				{
					this.OnTimeCardRecordIdChanging(value);
					this.SendPropertyChanging();
					this._TimeCardRecordId = value;
					this.SendPropertyChanged("TimeCardRecordId");
					this.OnTimeCardRecordIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegularHours", DbType="Decimal(18,6) NOT NULL")]
		public decimal RegularHours
		{
			get
			{
				return this._RegularHours;
			}
			set
			{
				if ((this._RegularHours != value))
				{
					this.OnRegularHoursChanging(value);
					this.SendPropertyChanging();
					this._RegularHours = value;
					this.SendPropertyChanged("RegularHours");
					this.OnRegularHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OvertimeHours", DbType="Decimal(18,6) NOT NULL")]
		public decimal OvertimeHours
		{
			get
			{
				return this._OvertimeHours;
			}
			set
			{
				if ((this._OvertimeHours != value))
				{
					this.OnOvertimeHoursChanging(value);
					this.SendPropertyChanging();
					this._OvertimeHours = value;
					this.SendPropertyChanged("OvertimeHours");
					this.OnOvertimeHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacationHours", DbType="Decimal(18,6) NOT NULL")]
		public decimal VacationHours
		{
			get
			{
				return this._VacationHours;
			}
			set
			{
				if ((this._VacationHours != value))
				{
					this.OnVacationHoursChanging(value);
					this.SendPropertyChanging();
					this._VacationHours = value;
					this.SendPropertyChanged("VacationHours");
					this.OnVacationHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHours", DbType="Decimal(18,6) NOT NULL")]
		public decimal TotalHours
		{
			get
			{
				return this._TotalHours;
			}
			set
			{
				if ((this._TotalHours != value))
				{
					this.OnTotalHoursChanging(value);
					this.SendPropertyChanging();
					this._TotalHours = value;
					this.SendPropertyChanged("TotalHours");
					this.OnTotalHoursChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmployeeId;
		
		private string _EmployeeName;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _SSN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this.OnEmployeeNameChanging(value);
					this.SendPropertyChanging();
					this._EmployeeName = value;
					this.SendPropertyChanged("EmployeeName");
					this.OnEmployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
